A.landing=A.map;
const CHAR=[
{name:'THE TRAVELER',line:'Ready for anything.',hair:'#171717',shirt:'#397a5c',accent:'#eab634'},
{name:'THE EXPLORER',line:"Let's see what's out there.",hair:'#392619',shirt:'#3b7189',accent:'#d3a846'},
{name:'THE UNCLE',line:'I packed snacks.',hair:'#33251f',shirt:'#8f653a',accent:'#e0c26b'},
{name:'THE GRANDMA',line:'No need to rush.',hair:'#b9b7aa',shirt:'#8d5575',accent:'#e8b9cc'},
{name:'THE KID',line:'Can we go now?',hair:'#292929',shirt:'#d58c31',accent:'#da4239'},
{name:'THE OLD FISHERMAN',line:'I know these waters.',hair:'#d4d0bd',shirt:'#3b6579',accent:'#d5a74e'},
{name:'PHU QUOC RIDGEBACK',line:'No ticket needed.',special:'dog'},
{name:'PEPPER',line:'A little spicy.',special:'pepper'}
];
document.getElementById('landingMap').src=A.landing;document.getElementById('mapImg').src=A.map;document.getElementById('airportBg').style.backgroundImage=`url("${A.airport}")`;document.getElementById('sideBg').style.backgroundImage=`url("${A.bg}")`;document.getElementById('gameBg').style.backgroundImage=`url("${A.bg}")`;document.getElementById('road').style.backgroundImage=`url("${A.road}")`;document.getElementById('fg').style.backgroundImage=`url("${A.foreground}")`;document.getElementById('player').style.backgroundImage=`url("${A.ride1}")`;document.getElementById('coin').style.backgroundImage=`url("${A.coin}")`;
let totalJo=+(localStorage.pqJo||0),selected=0;const views=[...document.querySelectorAll('.view')],grid=document.getElementById('charGrid');
function show(id){views.forEach(v=>v.classList.toggle('on',v.id===id));}
CHAR.forEach((c,i)=>{let b=document.createElement('button');b.className='char'+(i===0?' sel':'');let sp=c.special?` ${c.special}`:'';b.innerHTML=`<div class="face${sp}" style="--hair:${c.hair||'#171717'};--shirt:${c.shirt||'#397a5c'};--accent:${c.accent||'#eab634'}"><i class=headp></i><i class=bodyp></i><i class=acc></i></div><div class=copy><b>${c.name}</b><small>${c.line}</small></div>`;b.onclick=()=>{selected=i;[...grid.children].forEach((x,j)=>x.classList.toggle('sel',j===i))};grid.appendChild(b)});
function openMap(){let n=document.getElementById('playerName').value.trim()||'Traveler';document.getElementById('mapHello').textContent=`WELCOME, ${n.toUpperCase()}`;document.getElementById('mapJo').textContent=totalJo;show('map')}
function openGame(){show('gameView');document.getElementById('tutorial').classList.add('on');document.getElementById('over').classList.remove('on')}
function backMap(){stopGame();document.getElementById('tutorial').classList.remove('on');document.getElementById('over').classList.remove('on');document.getElementById('mapJo').textContent=totalJo;show('map')}

const lane=document.getElementById('lane'),player=document.getElementById('player'),shadow=document.getElementById('shadow'),ob=document.getElementById('ob'),coin=document.getElementById('coin'),road=document.getElementById('road'),fg=document.getElementById('fg'),speedEl=document.getElementById('speed'),scoreEl=document.getElementById('score'),joEl=document.getElementById('jo'),bestEl=document.getElementById('best'),toast=document.getElementById('toast'),helper=document.getElementById('helper'),level=document.getElementById('level'),over=document.getElementById('over');
let run=false,raf=0,last=0,scoreN=0,runJo=0,best=+(localStorage.pqBestR3||0),ox=0,cx=0,cur=null,jumpStart=0,jumpY=0,frame=0,frameT=0,world=0,audio=null,osc=null,gain=null,titleT=0,firstGrace=true;
bestEl.textContent='BEST '+best;
const obstacles=[{img:A.planter,w:72,h:70,hitW:42,hitH:42},{img:A.chair,w:58,h:70,hitW:28,hitH:43},{img:A.table,w:68,h:58,hitW:36,hitH:33},{img:A.menu,w:62,h:75,hitW:34,hitH:48},{img:A.tripod,w:66,h:76,hitW:28,hitH:47},{img:A.suitcase,w:52,h:64,hitW:30,hitH:40}];
function scale(){return lane.clientWidth/540}function diff(){if(scoreN<10)return{v:76,g:[650,820],label:'EASY'};if(scoreN<25)return{v:106,g:[430,570],label:'WARMING UP'};if(scoreN<50)return{v:130,g:[350,480],label:'GETTING QUICK'};return{v:150+Math.min(30,(scoreN-50)*.65),g:[300,410],label:'NO BRAKES'}}
function engStart(){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();engStop();osc=audio.createOscillator();gain=audio.createGain();osc.type='sawtooth';osc.frequency.value=66;gain.gain.value=.016;osc.connect(gain).connect(audio.destination);osc.start()}catch(e){}}function engStop(){try{if(osc)osc.stop();osc=null}catch(e){}}function tone(f=760,d=.08,v=.035){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();let o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch(e){}}
function flash(t){toast.textContent=t;toast.classList.remove('show');void toast.offsetWidth;toast.classList.add('show')}function choose(){let max=scoreN<10?3:obstacles.length;cur=obstacles[Math.floor(Math.random()*max)];let s=scale();ob.style.width=cur.w*s+'px';ob.style.height=cur.h*s+'px';ob.style.backgroundImage=`url("${cur.img}")`}function spawn(first=false){choose();let d=diff(),s=scale();ox=first?lane.clientWidth+d.v*8.2*s:lane.clientWidth+(d.g[0]+Math.random()*(d.g[1]-d.g[0]))*s;helper.textContent=d.label+(scoreN<10?' · FIRST 10 ARE FRIENDLY':'')}function spawnCoin(){let s=scale();cx=lane.clientWidth+(190+Math.random()*360)*s;coin.style.bottom=(195+Math.random()*85)*s+'px'}function hop(){if(!run||jumpStart)return;jumpStart=performance.now();tone(520,.055,.02)}
function physics(now){if(!jumpStart){jumpY=0;return}let s=scale(),p=Math.min(1,(now-jumpStart)/700),logical=96*4*p*(1-p);jumpY=logical*s;let rot=p<.5?-4*(p/.5):-4+7*((p-.5)/.5);player.style.transform=`translateY(${-jumpY}px) rotate(${rot}deg) scaleY(${p>.91?.96:1})`;shadow.style.transform=`scale(${1-logical/250},${1-logical/460})`;shadow.style.opacity=String(.6-logical/225);if(p>=1){jumpStart=0;jumpY=0;player.style.transform='';shadow.style.transform='';shadow.style.opacity='.6';tone(210,.045,.016)}}
function ride(dt){frameT+=dt;if(frameT>108){frameT=0;frame=(frame+1)%4;player.style.backgroundImage=`url("${A['ride'+(frame+1)]}")`}}function dust(){if(Math.random()>.18)return;let d=document.createElement('i');d.className='dust';let s=scale();d.style.left=122*s+'px';d.style.bottom=103*s+'px';lane.appendChild(d);let dx=0,a=.75,t=setInterval(()=>{dx-=3*s;a-=.09;d.style.transform=`translate(${dx}px,${-Math.abs(dx)*.18}px) scale(${1+(1-a)*.6})`;d.style.opacity=a;if(a<=0){clearInterval(t);d.remove()}},30)}
function startGame(){document.getElementById('tutorial').classList.remove('on');over.classList.remove('on');run=true;scoreN=0;runJo=0;jumpStart=0;jumpY=0;frame=0;frameT=0;world=0;firstGrace=true;scoreEl.textContent='SCORE 0';joEl.textContent='JO 0';level.classList.remove('fade');titleT=performance.now();last=performance.now();spawn(true);spawnCoin();engStart();raf=requestAnimationFrame(loop)}function stopGame(){run=false;cancelAnimationFrame(raf);engStop()}
function loop(t){if(!run)return;let dt=Math.min(34,t-last);last=t;let s=scale(),d=diff(),spd=d.v*s/1000;world+=dt*spd;ox-=dt*spd;cx-=dt*spd*.94;road.style.backgroundPositionX=(-world%(240*s))+'px';fg.style.backgroundPositionX=(-world*.28%(300*s))+'px';speedEl.classList.toggle('on',scoreN>=25);if(osc)osc.frequency.setValueAtTime(66+Math.min(28,scoreN*.35),audio.currentTime);ride(dt);physics(t);dust();ob.style.left=ox+'px';coin.style.left=cx+'px';if(t-titleT>2400)level.classList.add('fade');let ow=cur.w*s;if(ox<-ow){scoreN++;scoreEl.textContent='SCORE '+scoreN;if(scoreN===1)flash('EASY.');if(scoreN===10){flash('WARMING UP!');tone(900,.12,.035)}if(scoreN===25){flash('FASTER!');tone(1050,.12,.035)}if(scoreN===69){flash('NICE.');tone(690,.16,.04)}spawn(false)}if(cx<-60*s)spawnCoin();let pL=70*s+26*s,pR=70*s+102*s,hw=cur.hitW*s,hL=ox+(ow-hw)/2,hR=hL+hw,oh=cur.hitH*s,collide=pR>hL&&pL<hR;if(collide&&jumpY<oh*.74){if(firstGrace&&scoreN<2){firstGrace=false;ox+=145*s;flash('TAP TO HOP!');tone(430,.1,.022)}else{endGame();return}}let coinW=44*s;if(pR>cx&&pL<cx+coinW&&jumpY>38*s){runJo++;joEl.textContent='JO '+runJo;flash('+1 JO');tone(1180,.08,.035);spawnCoin()}raf=requestAnimationFrame(loop)}
function endGame(){run=false;cancelAnimationFrame(raf);engStop();best=Math.max(best,scoreN);localStorage.pqBestR3=best;totalJo+=runJo;localStorage.pqJo=totalJo;bestEl.textContent='BEST '+best;tone(145,.18,.04);document.getElementById('result').innerHTML=`SCORE <b>${scoreN}</b> · JO <b>+${runJo}</b><br><span class=small>${scoreN<3?'No rush. Watch the obstacle and hop a little earlier.':'Nice run.'}</span>`;over.classList.add('on')}
document.getElementById('gameView').addEventListener('pointerdown',()=>{if(run)hop()});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();hop()}});