const DATA_BASE='https://raw.githubusercontent.com/kenzuko/Jotrip-Lab/data-sunairport/data/sunairport';
const AUTO_REFRESH_MS=60*1000;
const state={latest:null,health:null,direction:'arrival',filter:'all',query:'',limit:8,mode:'live',lastFetchAt:0,loading:false};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

function vnNowParts(date=new Date()){
  const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Ho_Chi_Minh',hour:'2-digit',minute:'2-digit',hour12:false,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);
  const o={};p.forEach(x=>o[x.type]=x.value);return o;
}
function mins(t){if(!t)return null;const m=String(t).match(/(\d{1,2}):(\d{2})/);return m?+m[1]*60 + +m[2]:null}
function nowMinutes(){const p=vnNowParts();return +p.hour*60 + +p.minute}
function foldText(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').toUpperCase().replace(/\s+/g,' ').trim()}
function ageInfo(iso){if(!iso)return {level:'bad',label:'Không rõ',minutes:null};const m=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/60000));if(m<=8)return{level:'good',label:m+' phút',minutes:m};if(m<=15)return{level:'watch',label:m+' phút',minutes:m};return{level:'stale',label:m+' phút',minutes:m}}
function stationLabel(s){return (s||'').replace('HO CHI MINH','TP.HCM').replace('HA NOI','HÀ NỘI').replace('DA NANG','ĐÀ NẴNG').replace('HAI PHONG','HẢI PHÒNG').replace('CAN THO','CẦN THƠ').replace('CAM RANH','CAM RANH').replace('PUDONG- SHANGHAI','SHANGHAI').replace('XIANYANG-XI AN','XI\'AN')}
function airlineFromContext(c){const m=(c||'').match(/•\s*([^|]+)/);return m?m[1].trim():''}
function isDelayed(r){return /TRỄ|DELAYED|RESCHEDULED|HOÃN/i.test(r?.status||'')}
function isAbnormal(r){return /TRỄ|DELAYED|RESCHEDULED|HOÃN|HỦY|CANCELLED/i.test(r?.status||'')}
function statusClass(s){s=(s||'').toUpperCase();if(/ĐÃ HẠ CÁNH|ĐÃ CẤT CÁNH|BÃI ĐỖ/.test(s))return'green';if(/ĐÚNG GIỜ|LÀM THỦ TỤC|BOARDING/.test(s))return'blue';if(/TRỄ|CHẬM|DELAY|HOÃN|RESCHEDULED/.test(s))return'amber';if(/HỦY|CANCEL/.test(s))return'red';return'gray'}
function scheduledTime(r){return r?.scheduled_time||r?.times?.[0]||null}
function expectedTime(r){if(r?.estimated_time)return r.estimated_time;if(!isDelayed(r))return null;const ts=r?.times||[];return ts.length>1?ts[ts.length-1]:null}
function positiveTimeDiff(from,to){const a=mins(from),b=mins(to);if(a==null||b==null)return null;let d=b-a;if(d<0)d+=1440;return d>=0&&d<=720?d:null}
function snapshotMinutes(){const iso=state.latest?.collected_at_vn;if(!iso)return null;const p=vnNowParts(new Date(iso));return +p.hour*60 + +p.minute}
function timingInfo(r){
  const scheduled=scheduledTime(r),expected=expectedTime(r);
  let delay=Number.isFinite(Number(r?.delay_minutes))?Number(r.delay_minutes):null;
  if(delay==null&&expected&&expected!==scheduled)delay=positiveTimeDiff(scheduled,expected);
  let minimum=null;
  if(isDelayed(r)&&delay==null&&scheduled){
    const snap=snapshotMinutes(),sm=mins(scheduled);
    if(snap!=null&&sm!=null){let d=snap-sm;if(d<0&&sm>1200&&snap<240)d+=1440;if(d>=0&&d<=720)minimum=d;}
  }
  return {scheduled,expected,delay,minimum};
}
function delayStatusLabel(r){const t=timingInfo(r);if(!isDelayed(r))return r.status||'CHƯA RÕ';if(t.delay!=null)return `TRỄ ${t.delay} PHÚT`;if(t.minimum!=null&&t.minimum>0)return `TRỄ ≥ ${t.minimum} PHÚT`;return 'TRỄ'}
function isPastRecord(r){const t=mins(scheduledTime(r));if(t==null)return false;const now=nowMinutes();if(r.direction==='arrival'&&/ĐÃ HẠ CÁNH|BÃI ĐỖ/.test(r.status||''))return true;if(r.direction==='departure'&&/ĐÃ CẤT CÁNH/.test(r.status||''))return true;return t<now-45}
function isNext3(r){const t=mins(scheduledTime(r));if(t==null)return false;const d=t-nowMinutes();return d>=-30&&d<=180}
function changed(r){return isAbnormal(r)}

async function fetchJson(path){const res=await fetch(`${DATA_BASE}/${path}?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`${path}: HTTP ${res.status}`);return res.json()}
async function load(){
  if(state.loading)return;
  state.loading=true;setLoading(true);
  try{
    const [latest,health]=await Promise.all([fetchJson('latest.json'),fetchJson('health.json')]);
    state.latest=latest;state.health=health;state.lastFetchAt=Date.now();renderAll();$('#errorBox').classList.add('hidden');
  }catch(e){
    console.error(e);$('#errorBox').textContent='Không đọc được dữ liệu Sun Airport lúc này. Trang không hiển thị số cũ giả làm dữ liệu live.';$('#errorBox').classList.remove('hidden');setHealth('bad','MẤT DỮ LIỆU','Không thể tải snapshot hiện tại.');
  }finally{state.loading=false;setLoading(false)}
}
function setLoading(on){$('#refreshBtn').textContent=on?'…':'↻';$('#mobileRefresh').querySelector('span').textContent=on?'…':'↻'}
function setHealth(level,title,desc){const pill=$('#healthPill');pill.className='health-pill '+level;pill.textContent=title;const icon=$('#healthIcon');icon.className='health-icon '+level;icon.textContent=level==='good'?'✓':level==='watch'||level==='stale'?'!':'×';$('#healthTitle').textContent=title;$('#healthDescription').textContent=desc}
function renderAll(){renderSummary();renderHealth();renderFlights();renderNextWindow();renderWatch();renderNextArrivals();renderAnalytics()}
function renderSummary(){const l=state.latest;$('#totalFlights').textContent=l.counts?.total??'-';$('#arrivalsCount').textContent=l.counts?.arrivals??'-';$('#departuresCount').textContent=l.counts?.departures??'-';$('#internationalCount').textContent=l.summary?.arrivals_market?.international??'-';const age=ageInfo(l.collected_at_vn);$('#updatedAt').textContent=`Cập nhật ${new Date(l.collected_at_vn).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Ho_Chi_Minh'})} · ${age.label} trước · tự làm mới 1 phút`;const abnormal=(l.records||[]).filter(r=>!isPastRecord(r)&&changed(r)).length;const ops=$('#opsState');ops.className='ops-state';if(age.level==='stale'||age.level==='bad'){ops.textContent='DATA STALE';ops.classList.add('bad')}else if(abnormal>0||age.level==='watch'){ops.textContent='WATCH · '+abnormal+' BẤT THƯỜNG';ops.classList.add('watch')}else ops.textContent='OPERATIONS NORMAL'}
function renderHealth(){const l=state.latest,h=state.health,age=ageInfo(l.collected_at_vn);const qa=!!(h?.collector_completed&&h?.parser_passed&&h?.normalization_passed&&h?.qa_passed&&l?.quality?.usable);$('#qaText').textContent=qa?'PASS':'FAIL';$('#qaBadge').textContent=qa?'QA PASS':'QA FAIL';$('#qaBadge').className='qa-badge '+(qa?'good':'bad');$('#dataAge').textContent=age.label;let title,desc,level=age.level;if(!qa){level='bad';title='QA FAILED';desc='Collector hoặc parser/normalization chưa đạt. Không nên dùng số liệu để điều hành.'}else if(age.level==='good'){title='GOOD · dữ liệu đang mới';desc='Snapshot đã qua parser, normalization và QA. Có thể dùng cho bảng điều hành.'}else if(age.level==='watch'){title='WATCH · dữ liệu chậm cập nhật';desc='Snapshot vẫn hợp lệ nhưng đã quá 8 phút. Trang tự kiểm tra bản mới mỗi 1 phút.'}else{title='STALE · không còn là dữ liệu live';desc='Snapshot đã quá 15 phút. Không nên xem đây là trạng thái tức thời của sân bay.'}setHealth(level,title,desc)}
function recordsFiltered(){let a=[...(state.latest?.records||[])];if(state.direction!=='all')a=a.filter(r=>r.direction===state.direction);if(state.filter==='next3')a=a.filter(isNext3);if(state.filter==='international')a=a.filter(r=>r.market==='international');if(state.filter==='domestic')a=a.filter(r=>r.market==='domestic');if(state.filter==='changed')a=a.filter(changed);if(state.query){const q=foldText(state.query);a=a.filter(r=>foldText([r.operating_flight_number,...(r.marketing_flight_numbers||[]),r.station,stationLabel(r.station),airlineFromContext(r.context),r.status,r.context].join(' ')).includes(q))}a.sort((x,y)=>(mins(scheduledTime(x))??9999)-(mins(scheduledTime(y))??9999));return a}
function rowHtml(r){const info=timingInfo(r),t=info.scheduled||'--:--',air=airlineFromContext(r.context),to=r.direction==='arrival'?'PQC':stationLabel(r.station),from=r.direction==='arrival'?stationLabel(r.station):'PQC';let timeSub=r.direction==='arrival'?'Đến PQC':'Rời PQC';if(isDelayed(r))timeSub=info.expected?`Dự kiến ${info.expected}`:'Chưa có giờ dự kiến';const status=isDelayed(r)?delayStatusLabel(r):(r.status||'CHƯA RÕ');return `<div class="flight-row" data-flight="${escapeHtml(r.operating_flight_number)}" data-direction="${r.direction}"><div class="flight-number">${escapeHtml(r.operating_flight_number||'')}</div><div class="flight-time">${escapeHtml(t)}<small>${escapeHtml(timeSub)}</small></div><div class="route">${escapeHtml(from)} → ${escapeHtml(to)}<small>${escapeHtml(air)}</small></div><div class="market-label">${r.market==='international'?'Quốc tế':'Nội địa'}</div><div class="status-pill ${statusClass(r.status)}">${escapeHtml(status)}</div><div class="chevron">›</div></div>`}
function renderFlights(){const list=recordsFiltered(),visible=list.slice(0,state.limit);$('#flightList').innerHTML=visible.length?visible.map(rowHtml).join(''):'<div class="empty-state">Không có chuyến phù hợp bộ lọc hiện tại.</div>';$('#showMore').classList.toggle('hidden',list.length<=state.limit);$$('.flight-row').forEach(el=>el.onclick=()=>openDrawer(el.dataset.flight,el.dataset.direction))}
function renderNextWindow(){const all=state.latest?.records||[],next=all.filter(isNext3).filter(r=>!isPastRecord(r));$('#nextArrivals').textContent=next.filter(r=>r.direction==='arrival').length;$('#nextDepartures').textContent=next.filter(r=>r.direction==='departure').length;$('#nextInternational').textContent=next.filter(r=>r.direction==='arrival'&&r.market==='international').length;$('#nextWatch').textContent=next.filter(changed).length;const p=vnNowParts();$('#nextWindowText').textContent=`Từ ${p.hour}:${p.minute}`}
function renderWatch(){const age=ageInfo(state.latest?.collected_at_vn);let items=(state.latest?.records||[]).filter(r=>!isPastRecord(r)&&changed(r)).slice(0,6).map(r=>{const t=timingInfo(r);let detail=r.status||'Trạng thái chưa rõ';if(isDelayed(r)){detail=delayStatusLabel(r);detail+=t.expected?` · dự kiến ${t.expected}`:' · chưa có giờ dự kiến';}return{title:`${r.operating_flight_number} · ${r.direction==='arrival'?stationLabel(r.station)+' → PQC':'PQC → '+stationLabel(r.station)}`,body:`${t.scheduled||'--:--'} · ${detail}`}});if(age.level==='stale')items.unshift({title:'Snapshot đã stale',body:`Dữ liệu cuối cùng cách hiện tại ${age.label}. Không nên dùng để kết luận trạng thái tức thời.`});$('#watchCount').textContent=items.length;$('#watchList').innerHTML=items.length?items.map(x=>`<div class="watch-item"><div class="watch-icon">!</div><div><strong>${escapeHtml(x.title)}</strong><p>${escapeHtml(x.body)}</p></div></div>`).join(''):'<div class="empty-state">Không có bất thường nổi bật trong snapshot hiện tại.</div>'}
function renderNextArrivals(){const a=(state.latest?.records||[]).filter(r=>r.direction==='arrival'&&!isPastRecord(r)).sort((x,y)=>(mins(scheduledTime(x))??9999)-(mins(scheduledTime(y))??9999)).slice(0,5);$('#nextArrivalsList').innerHTML=a.length?a.map(r=>{const info=timingInfo(r),status=isDelayed(r)?delayStatusLabel(r):(r.status||'');return `<div class="arrival-item"><div class="arrival-time">${escapeHtml(info.scheduled||'--:--')}</div><div class="arrival-main"><strong>${escapeHtml(r.operating_flight_number)} · ${escapeHtml(stationLabel(r.station))}</strong><span>${escapeHtml(isDelayed(r)&&info.expected?'Dự kiến '+info.expected:airlineFromContext(r.context))}</span></div><span class="status-pill ${statusClass(r.status)}">${escapeHtml(status)}</span></div>`}).join(''):'<div class="empty-state">Chưa có chuyến đến tiếp theo trong snapshot.</div>'}
function pct(v,total){return total?Math.round(v*1000/total)/10+'%':'0%'}
function renderAnalytics(){const s=state.latest?.summary||{},am=s.arrivals_market||{},dm=s.departures_market||{};$('#aIntlArr').textContent=am.international??0;$('#aDomArr').textContent=am.domestic??0;$('#aIntlDep').textContent=dm.international??0;$('#aDomDep').textContent=dm.domestic??0;$('#aIntlArrPct').textContent=pct(am.international||0,state.latest?.counts?.arrivals||0)+' chuyến đến';$('#aDomArrPct').textContent=pct(am.domestic||0,state.latest?.counts?.arrivals||0)+' chuyến đến';$('#aIntlDepPct').textContent=pct(dm.international||0,state.latest?.counts?.departures||0)+' chuyến đi';$('#aDomDepPct').textContent=pct(dm.domestic||0,state.latest?.counts?.departures||0)+' chuyến đi';const merged={};for(const [k,v] of Object.entries(s.arrivals_by_station||{}))merged[k]=(merged[k]||0)+v;for(const [k,v] of Object.entries(s.departures_by_station||{}))merged[k]=(merged[k]||0)+v;const routes=Object.entries(merged).sort((a,b)=>b[1]-a[1]).slice(0,7),max=routes[0]?.[1]||1;$('#routeBars').innerHTML=routes.map(([k,v])=>`<div class="route-bar"><span>${escapeHtml(stationLabel(k))}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join('');const banks=s.arrivals_by_time_bank||{},ordered=['00:00-05:59','06:00-08:59','09:00-11:59','12:00-14:59','15:00-17:59','18:00-20:59','21:00-23:59'];const mx=Math.max(1,...ordered.map(k=>banks[k]||0));$('#timeBankBars').innerHTML=ordered.map(k=>`<div class="time-col"><div class="bar" style="height:${(banks[k]||0)/mx*100}%" title="${banks[k]||0} chuyến"></div><span>${k.slice(0,2)}h</span></div>`).join('');const statuses={};for(const [k,v] of Object.entries(s.arrivals_by_status||{}))statuses['Đến · '+k]=v;for(const [k,v] of Object.entries(s.departures_by_status||{}))statuses['Đi · '+k]=v;$('#statusSummary').innerHTML=Object.entries(statuses).map(([k,v])=>`<div class="status-line"><span>${escapeHtml(k)}</span><b>${v}</b></div>`).join('')}
function openDrawer(flight,direction){const r=(state.latest?.records||[]).find(x=>x.operating_flight_number===flight&&x.direction===direction);if(!r)return;const air=airlineFromContext(r.context),info=timingInfo(r),landed=/ĐÃ HẠ CÁNH|BÃI ĐỖ/.test(r.status||''),departed=/ĐÃ CẤT CÁNH/.test(r.status||''),a=r.direction==='arrival';let delayText='Không trễ';if(isDelayed(r)){if(info.delay!=null)delayText=`${info.delay} phút`;else if(info.minimum!=null&&info.minimum>0)delayText=`Ít nhất ${info.minimum} phút tại thời điểm snapshot`;else delayText='Đã báo trễ, chưa xác định số phút';}const expectedText=info.expected|| (isDelayed(r)?'Sân bay chưa công bố':'Không áp dụng');$('#drawerContent').innerHTML=`<div class="drawer-title">${a?'CHUYẾN ĐẾN':'CHUYẾN ĐI'}</div><h2 class="drawer-flight">${escapeHtml(r.operating_flight_number)}</h2><div class="drawer-route">${a?escapeHtml(stationLabel(r.station))+' → PQC':'PQC → '+escapeHtml(stationLabel(r.station))}</div><div class="journey"><div class="journey-dot done"></div><div class="journey-copy"><strong>Theo lịch · ${escapeHtml(info.scheduled||'--:--')}</strong><p>${escapeHtml(air)}</p></div><div class="journey-dot ${landed||departed?'done':''}"></div><div class="journey-copy"><strong>${escapeHtml(isDelayed(r)?delayStatusLabel(r):(r.status||'Chưa có trạng thái'))}</strong><p>Trạng thái lấy trực tiếp từ bảng chuyến bay Sun Airport.</p></div><div class="journey-dot last"></div><div class="journey-copy"><strong>Dự kiến · ${escapeHtml(expectedText)}</strong><p>${isDelayed(r)&&!info.expected?'Nguồn hiện tại chỉ báo TRỄ, chưa có ETA nên JoTrip không tự đoán giờ đến.':'Giờ cập nhật lấy từ dữ liệu sân bay.'}</p></div></div><div class="drawer-meta"><div><span>Độ trễ</span><b>${escapeHtml(delayText)}</b></div><div><span>Thị trường</span><b>${r.market==='international'?'Quốc tế':'Nội địa'}</b></div><div><span>Snapshot</span><b>${escapeHtml(state.latest.page_last_updated||state.latest.collected_at_vn||'')}</b></div><div><span>Nguồn</span><b>Sun Airport - PQC</b></div></div>`;$('#drawerBackdrop').classList.remove('hidden');$('#flightDrawer').classList.remove('hidden');$('#flightDrawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('#drawerBackdrop').classList.add('hidden');$('#flightDrawer').classList.add('hidden');$('#flightDrawer').setAttribute('aria-hidden','true')}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setMode(mode){state.mode=mode;$('#app').classList.toggle('mode-analytics',mode==='analytics');$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$$('[data-mobile-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mobileMode===mode));window.scrollTo({top:0,behavior:'smooth'})}

// Search is a primary operation, so keep it visible. Matching is accent-insensitive in both directions.
$('#searchWrap').classList.remove('hidden');$('#searchToggle').classList.add('hidden');$('#flightSearch').placeholder='Tìm số chuyến, hãng hoặc nơi đi/đến: VJ339, Hà Nội, Da Nang...';
const extraStyle=document.createElement('style');extraStyle.textContent=`.search-wrap{margin:0 0 12px}.search-wrap input{height:48px;padding-left:42px;background:#f9fcfd;border-color:#d8e6ee}.search-wrap{position:relative}.search-wrap:before{content:'⌕';position:absolute;left:15px;top:9px;font-size:24px;color:#72869a;z-index:1}.status-pill.amber{font-weight:950}@media(max-width:680px){.search-wrap input{font-size:16px;height:48px}.status-pill{max-width:118px;overflow:hidden;text-overflow:ellipsis}}`;document.head.appendChild(extraStyle);

$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
$$('[data-mobile-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mobileMode));
$$('#directionTabs button').forEach(b=>b.onclick=()=>{state.direction=b.dataset.direction;state.limit=8;$$('#directionTabs button').forEach(x=>x.classList.toggle('active',x===b));renderFlights()});
$$('#filterChips button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;state.limit=8;$$('#filterChips button').forEach(x=>x.classList.toggle('active',x===b));renderFlights()});
$('#flightSearch').oninput=e=>{state.query=e.target.value.trim();state.limit=8;renderFlights()};
$('#showMore').onclick=()=>{state.limit+=10;renderFlights()};
$('#refreshBtn').onclick=load;$('#mobileRefresh').onclick=load;
$('#mobileFlights').onclick=()=>{setMode('live');document.querySelector('.card.live-only')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>$('#flightSearch')?.focus(),350)};
$('#drawerBackdrop').onclick=closeDrawer;$('#drawerClose').onclick=closeDrawer;
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#flightDrawer').classList.contains('hidden'))closeDrawer();else if(document.activeElement===$('#flightSearch')){$('#flightSearch').value='';state.query='';renderFlights();}}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&Date.now()-state.lastFetchAt>60*1000)load()});
window.addEventListener('online',load);
load();
setInterval(()=>load(),AUTO_REFRESH_MS);
setInterval(()=>{if(state.latest){renderSummary();renderHealth();renderNextWindow();renderWatch();renderNextArrivals()}},60000);
