const DATA_BASE='https://raw.githubusercontent.com/kenzuko/Jotrip-Lab/data-sunairport/data/sunairport';
const state={latest:null,health:null,direction:'arrival',filter:'all',query:'',limit:8,mode:'live'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaultStatus=s=>/^(ĐÚNG GIỜ|LÀM THỦ TỤC LÚC)$/i.test((s||'').trim());
function vnNowParts(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Ho_Chi_Minh',hour:'2-digit',minute:'2-digit',hour12:false,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o={};p.forEach(x=>o[x.type]=x.value);return o}
function mins(t){if(!t)return null;const m=String(t).match(/(\d{1,2}):(\d{2})/);return m?+m[1]*60 + +m[2]:null}
function nowMinutes(){const p=vnNowParts();return +p.hour*60 + +p.minute}
function ageInfo(iso){if(!iso)return {level:'bad',label:'Không rõ',minutes:null};const m=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/60000));if(m<=30)return{level:'good',label:m+' phút',minutes:m};if(m<=90)return{level:'watch',label:m+' phút',minutes:m};return{level:'stale',label:m+' phút',minutes:m}}
function stationLabel(s){return (s||'').replace('HO CHI MINH','TP.HCM').replace('HA NOI','HÀ NỘI').replace('PUDONG- SHANGHAI','SHANGHAI').replace('XIANYANG-XI AN','XI\'AN')}
function airlineFromContext(c){const m=(c||'').match(/•\s*([^|]+)/);return m?m[1].trim():''}
function statusClass(s){s=(s||'').toUpperCase();if(/ĐÃ HẠ CÁNH|ĐÃ CẤT CÁNH|BÃI ĐỖ/.test(s))return'green';if(/ĐÚNG GIỜ|LÀM THỦ TỤC/.test(s))return'blue';if(/TRỄ|CHẬM|DELAY/.test(s))return'amber';if(/HỦY|CANCEL/.test(s))return'red';return'gray'}
function isPastRecord(r){const t=mins(r.times?.[0]);if(t==null)return false;const now=nowMinutes();if(r.direction==='arrival'&&/ĐÃ HẠ CÁNH|BÃI ĐỖ/.test(r.status||''))return true;if(r.direction==='departure'&&/ĐÃ CẤT CÁNH/.test(r.status||''))return true;return t<now-45}
function isNext3(r){const t=mins(r.times?.[0]);if(t==null)return false;let d=t-nowMinutes();if(d<-30)d+=1440;return d>=-30&&d<=180}
function changed(r){return !defaultStatus(r.status)}
async function fetchJson(path){const res=await fetch(`${DATA_BASE}/${path}?t=${Date.now()}`,{cache:'no-store'});if(!res.ok)throw new Error(`${path}: HTTP ${res.status}`);return res.json()}
async function load(){setLoading(true);try{const [latest,health]=await Promise.all([fetchJson('latest.json'),fetchJson('health.json')]);state.latest=latest;state.health=health;renderAll();$('#errorBox').classList.add('hidden')}catch(e){console.error(e);$('#errorBox').textContent='Không đọc được dữ liệu Sun Airport lúc này. Trang không hiển thị số cũ giả làm dữ liệu live.';$('#errorBox').classList.remove('hidden');setHealth('bad','MẤT DỮ LIỆU','Không thể tải snapshot hiện tại.');}finally{setLoading(false)}}
function setLoading(on){$('#refreshBtn').textContent=on?'…':'↻';$('#mobileRefresh').querySelector('span').textContent=on?'…':'↻'}
function setHealth(level,title,desc){const pill=$('#healthPill');pill.className='health-pill '+level;pill.textContent=title;const icon=$('#healthIcon');icon.className='health-icon '+level;icon.textContent=level==='good'?'✓':level==='watch'||level==='stale'?'!':'×';$('#healthTitle').textContent=title;$('#healthDescription').textContent=desc}
function renderAll(){renderSummary();renderHealth();renderFlights();renderNextWindow();renderWatch();renderNextArrivals();renderAnalytics();}
function renderSummary(){const l=state.latest;$('#totalFlights').textContent=l.counts?.total??'-';$('#arrivalsCount').textContent=l.counts?.arrivals??'-';$('#departuresCount').textContent=l.counts?.departures??'-';$('#internationalCount').textContent=l.summary?.arrivals_market?.international??'-';const age=ageInfo(l.collected_at_vn);$('#updatedAt').textContent=`Cập nhật ${new Date(l.collected_at_vn).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Ho_Chi_Minh'})} · ${age.label} trước`;const abnormal=(l.records||[]).filter(r=>!isPastRecord(r)&&changed(r)).length;const ops=$('#opsState');ops.className='ops-state';if(age.level==='stale'||age.level==='bad'){ops.textContent='DATA STALE';ops.classList.add('bad')}else if(abnormal>0||age.level==='watch'){ops.textContent='WATCH · '+abnormal+' THAY ĐỔI';ops.classList.add('watch')}else ops.textContent='OPERATIONS NORMAL'}
function renderHealth(){const l=state.latest,h=state.health,age=ageInfo(l.collected_at_vn);const qa=!!(h?.collector_completed&&h?.parser_passed&&h?.normalization_passed&&h?.qa_passed&&l?.quality?.usable);$('#qaText').textContent=qa?'PASS':'FAIL';$('#qaBadge').textContent=qa?'QA PASS':'QA FAIL';$('#qaBadge').className='qa-badge '+(qa?'good':'bad');$('#dataAge').textContent=age.label;let title,desc,level=age.level;if(!qa){level='bad';title='QA FAILED';desc='Collector hoặc parser/normalization chưa đạt. Không nên dùng số liệu để điều hành.'}else if(age.level==='good'){title='GOOD · dữ liệu đang mới';desc='Snapshot đã qua parser, normalization và QA. Có thể dùng cho bảng điều hành.'}else if(age.level==='watch'){title='WATCH · dữ liệu đang cũ dần';desc='Snapshot hợp lệ nhưng tuổi dữ liệu vượt ngưỡng live. Cần chờ lần đồng bộ kế tiếp.'}else{title='STALE · không còn là dữ liệu live';desc='Snapshot vẫn hợp lệ về cấu trúc nhưng đã quá cũ để xem như trạng thái sân bay hiện tại.'}setHealth(level,title,desc)}
function recordsFiltered(){let a=[...(state.latest?.records||[])];if(state.direction!=='all')a=a.filter(r=>r.direction===state.direction);if(state.filter==='next3')a=a.filter(isNext3);if(state.filter==='international')a=a.filter(r=>r.market==='international');if(state.filter==='domestic')a=a.filter(r=>r.market==='domestic');if(state.filter==='changed')a=a.filter(changed);if(state.query){const q=state.query.toUpperCase();a=a.filter(r=>[r.operating_flight_number,r.station,airlineFromContext(r.context),r.status].join(' ').toUpperCase().includes(q))}a.sort((x,y)=>(mins(x.times?.[0])??9999)-(mins(y.times?.[0])??9999));return a}
function rowHtml(r){const t=r.times?.[0]||'--:--',air=airlineFromContext(r.context),to=r.direction==='arrival'?'PQC':stationLabel(r.station),from=r.direction==='arrival'?stationLabel(r.station):'PQC';return `<div class="flight-row" data-flight="${escapeHtml(r.operating_flight_number)}" data-direction="${r.direction}"><div class="flight-number">${escapeHtml(r.operating_flight_number||'')}</div><div class="flight-time">${escapeHtml(t)}<small>${r.direction==='arrival'?'Đến PQC':'Rời PQC'}</small></div><div class="route">${escapeHtml(from)} → ${escapeHtml(to)}<small>${escapeHtml(air)}</small></div><div class="market-label">${r.market==='international'?'Quốc tế':'Nội địa'}</div><div class="status-pill ${statusClass(r.status)}">${escapeHtml(r.status||'CHƯA RÕ')}</div><div class="chevron">›</div></div>`}
function renderFlights(){const list=recordsFiltered(),visible=list.slice(0,state.limit);$('#flightList').innerHTML=visible.length?visible.map(rowHtml).join(''):'<div class="empty-state">Không có chuyến phù hợp bộ lọc hiện tại.</div>';$('#showMore').classList.toggle('hidden',list.length<=state.limit);$$('.flight-row').forEach(el=>el.onclick=()=>openDrawer(el.dataset.flight,el.dataset.direction))}
function renderNextWindow(){const all=state.latest?.records||[],next=all.filter(isNext3).filter(r=>!isPastRecord(r));$('#nextArrivals').textContent=next.filter(r=>r.direction==='arrival').length;$('#nextDepartures').textContent=next.filter(r=>r.direction==='departure').length;$('#nextInternational').textContent=next.filter(r=>r.direction==='arrival'&&r.market==='international').length;$('#nextWatch').textContent=next.filter(changed).length;const p=vnNowParts();$('#nextWindowText').textContent=`Từ ${p.hour}:${p.minute}`}
function renderWatch(){const age=ageInfo(state.latest?.collected_at_vn);let items=(state.latest?.records||[]).filter(r=>!isPastRecord(r)&&changed(r)).slice(0,6).map(r=>({title:`${r.operating_flight_number} · ${r.direction==='arrival'?stationLabel(r.station)+' → PQC':'PQC → '+stationLabel(r.station)}`,body:`${r.times?.[0]||'--:--'} · ${r.status||'Trạng thái chưa rõ'}`}));if(age.level==='stale')items.unshift({title:'Snapshot đã stale',body:`Dữ liệu cuối cùng cách hiện tại ${age.label}. Không nên dùng để kết luận trạng thái tức thời.`});$('#watchCount').textContent=items.length;$('#watchList').innerHTML=items.length?items.map(x=>`<div class="watch-item"><div class="watch-icon">!</div><div><strong>${escapeHtml(x.title)}</strong><p>${escapeHtml(x.body)}</p></div></div>`).join(''):'<div class="empty-state">Không có bất thường nổi bật trong snapshot hiện tại.</div>'}
function renderNextArrivals(){const a=(state.latest?.records||[]).filter(r=>r.direction==='arrival'&&!isPastRecord(r)).sort((x,y)=>(mins(x.times?.[0])??9999)-(mins(y.times?.[0])??9999)).slice(0,5);$('#nextArrivalsList').innerHTML=a.length?a.map(r=>`<div class="arrival-item"><div class="arrival-time">${escapeHtml(r.times?.[0]||'--:--')}</div><div class="arrival-main"><strong>${escapeHtml(r.operating_flight_number)} · ${escapeHtml(stationLabel(r.station))}</strong><span>${escapeHtml(airlineFromContext(r.context))}</span></div><span class="status-pill ${statusClass(r.status)}">${escapeHtml(r.status||'')}</span></div>`).join(''):'<div class="empty-state">Chưa có chuyến đến tiếp theo trong snapshot.</div>'}
function pct(v,total){return total?Math.round(v*1000/total)/10+'%':'0%'}
function renderAnalytics(){const s=state.latest?.summary||{},am=s.arrivals_market||{},dm=s.departures_market||{};$('#aIntlArr').textContent=am.international??0;$('#aDomArr').textContent=am.domestic??0;$('#aIntlDep').textContent=dm.international??0;$('#aDomDep').textContent=dm.domestic??0;$('#aIntlArrPct').textContent=pct(am.international||0,state.latest?.counts?.arrivals||0)+' chuyến đến';$('#aDomArrPct').textContent=pct(am.domestic||0,state.latest?.counts?.arrivals||0)+' chuyến đến';$('#aIntlDepPct').textContent=pct(dm.international||0,state.latest?.counts?.departures||0)+' chuyến đi';$('#aDomDepPct').textContent=pct(dm.domestic||0,state.latest?.counts?.departures||0)+' chuyến đi';const merged={};for(const [k,v] of Object.entries(s.arrivals_by_station||{}))merged[k]=(merged[k]||0)+v;for(const [k,v] of Object.entries(s.departures_by_station||{}))merged[k]=(merged[k]||0)+v;const routes=Object.entries(merged).sort((a,b)=>b[1]-a[1]).slice(0,7),max=routes[0]?.[1]||1;$('#routeBars').innerHTML=routes.map(([k,v])=>`<div class="route-bar"><span>${escapeHtml(stationLabel(k))}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><b>${v}</b></div>`).join('');const banks=s.arrivals_by_time_bank||{},ordered=['00:00-05:59','06:00-08:59','09:00-11:59','12:00-14:59','15:00-17:59','18:00-20:59','21:00-23:59'];const mx=Math.max(1,...ordered.map(k=>banks[k]||0));$('#timeBankBars').innerHTML=ordered.map(k=>`<div class="time-col"><div class="bar" style="height:${(banks[k]||0)/mx*100}%" title="${banks[k]||0} chuyến"></div><span>${k.slice(0,2)}h</span></div>`).join('');const statuses={};for(const [k,v] of Object.entries(s.arrivals_by_status||{}))statuses['Đến · '+k]=v;for(const [k,v] of Object.entries(s.departures_by_status||{}))statuses['Đi · '+k]=v;$('#statusSummary').innerHTML=Object.entries(statuses).map(([k,v])=>`<div class="status-line"><span>${escapeHtml(k)}</span><b>${v}</b></div>`).join('')}
function openDrawer(flight,direction){const r=(state.latest?.records||[]).find(x=>x.operating_flight_number===flight&&x.direction===direction);if(!r)return;const air=airlineFromContext(r.context),t=r.times?.[0]||'--:--',landed=/ĐÃ HẠ CÁNH|BÃI ĐỖ/.test(r.status||''),departed=/ĐÃ CẤT CÁNH/.test(r.status||'');const a=r.direction==='arrival';$('#drawerContent').innerHTML=`<div class="drawer-title">${a?'CHUYẾN ĐẾN':'CHUYẾN ĐI'}</div><h2 class="drawer-flight">${escapeHtml(r.operating_flight_number)}</h2><div class="drawer-route">${a?escapeHtml(stationLabel(r.station))+' → PQC':'PQC → '+escapeHtml(stationLabel(r.station))}</div><div class="journey"><div class="journey-dot done"></div><div class="journey-copy"><strong>Theo lịch · ${escapeHtml(t)}</strong><p>${escapeHtml(air)}</p></div><div class="journey-dot ${landed||departed?'done':''}"></div><div class="journey-copy"><strong>${escapeHtml(r.status||'Chưa có trạng thái')}</strong><p>Trạng thái lấy trực tiếp từ bảng chuyến bay Sun Airport.</p></div><div class="journey-dot last"></div><div class="journey-copy"><strong>Aircraft tracking</strong><p>Chưa có nguồn vị trí máy bay trong data plane hiện tại.</p></div></div><div class="drawer-note">JoTrip Airport Live không suy diễn vị trí máy bay. Khi chưa có nguồn tracking độc lập, trang chỉ hiển thị trạng thái đã xác minh từ sân bay.</div><div class="drawer-meta"><div><span>Thị trường</span><b>${r.market==='international'?'Quốc tế':'Nội địa'}</b></div><div><span>Snapshot</span><b>${escapeHtml(state.latest.page_last_updated||state.latest.collected_at_vn||'')}</b></div><div><span>Nguồn</span><b>Sun Airport - PQC</b></div></div>`;$('#drawerBackdrop').classList.remove('hidden');$('#flightDrawer').classList.remove('hidden');$('#flightDrawer').setAttribute('aria-hidden','false')}
function closeDrawer(){$('#drawerBackdrop').classList.add('hidden');$('#flightDrawer').classList.add('hidden');$('#flightDrawer').setAttribute('aria-hidden','true')}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setMode(mode){state.mode=mode;$('#app').classList.toggle('mode-analytics',mode==='analytics');$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$$('[data-mobile-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mobileMode===mode));window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-mobile-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mobileMode));$$('#directionTabs button').forEach(b=>b.onclick=()=>{state.direction=b.dataset.direction;state.limit=8;$$('#directionTabs button').forEach(x=>x.classList.toggle('active',x===b));renderFlights()});$$('#filterChips button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;state.limit=8;$$('#filterChips button').forEach(x=>x.classList.toggle('active',x===b));renderFlights()});$('#searchToggle').onclick=()=>{$('#searchWrap').classList.toggle('hidden');if(!$('#searchWrap').classList.contains('hidden'))$('#flightSearch').focus()};$('#flightSearch').oninput=e=>{state.query=e.target.value.trim();state.limit=8;renderFlights()};$('#showMore').onclick=()=>{state.limit+=10;renderFlights()};$('#refreshBtn').onclick=load;$('#mobileRefresh').onclick=load;$('#mobileFlights').onclick=()=>{setMode('live');document.querySelector('.card.live-only')?.scrollIntoView({behavior:'smooth',block:'start'})};$('#drawerBackdrop').onclick=closeDrawer;$('#drawerClose').onclick=closeDrawer;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});load();setInterval(()=>{if(state.latest){renderSummary();renderHealth();renderNextWindow()}},60000);