const DATA_BASE='https://raw.githubusercontent.com/kenzuko/Jotrip-Lab/data-sunairport/data/sunairport';
const $=s=>document.querySelector(s);
const state={raw:null,events:[],date:null,direction:'all',time:'all',query:''};

function vnDate(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o={};p.forEach(x=>o[x.type]=x.value);return `${o.year}-${o.month}-${o.day}`}
function fold(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').toUpperCase().replace(/\s+/g,' ').trim()}
function hhmm(v){const m=String(v??'').match(/^(\d{2})(\d{2})/);return m?`${m[1]}:${m[2]}`:null}
function mins(v){const t=hhmm(v)||String(v||'');const m=t.match(/^(\d{1,2}):(\d{2})$/);return m?+m[1]*60 + +m[2]:null}
function diff(a,b){const x=mins(a),y=mins(b);if(x==null||y==null)return null;let d=y-x;if(d>720)d-=1440;if(d<-720)d+=1440;return d}
function key(direction,row){return row?.id!=null?`${direction}|id:${row.id}`:`${direction}|${fold(row?.flightNo)}|${row?.scheduledTime||''}|${fold(row?.cityName)}`}
function sourceStatus(r){return String(r.notesVn||r.notesEn||r.status||r.remarks||'').trim()}
function checkinTime(text){const m=String(text||'').match(/LÀM THỦ TỤC LÚC\s*(\d{1,2}:\d{2})/i);return m?m[1]:null}
function humanStatus(r){const raw=sourceStatus(r),u=fold(raw),ci=checkinTime(raw);if(ci)return `Check-in từ ${ci}`;if(u.includes('DANG LAM THU TUC'))return 'Đang check-in';if(u.includes('QUAY THU TUC DA DONG'))return 'Check-in đã đóng';if(u.includes('CUA KHOI HANH DA DONG'))return 'Cửa khởi hành đã đóng';if(u.includes('HANH KHACH DANG LEN TAU BAY')||u.includes('BOARDING'))return 'Đang lên máy bay';if(u.includes('DA HA CANH')||u.includes('ARRIVED'))return 'Đã hạ cánh';if(u.includes('DA CAT CANH')||u.includes('DEPARTED'))return 'Đã cất cánh';if(u.includes('HUY')||u.includes('CANCEL'))return 'Đã hủy';if(u.includes('TRE')||u.includes('DELAY')||u.includes('DOI GIO')||u.includes('RESCHEDULED')){const s=hhmm(r.scheduledTime),e=hhmm(r.estimatedTime),d=diff(s,e);return d>0?`Trễ ${d} phút`:'Trễ / đổi giờ'}return raw||'Chưa có trạng thái'}
function statusClass(r){const u=fold(sourceStatus(r));if(/HUY|CANCEL/.test(u))return'red';if(/TRE|DELAY|DOI GIO|RESCHEDULED/.test(u)||(hhmm(r.estimatedTime)&&hhmm(r.estimatedTime)!==hhmm(r.scheduledTime)))return'amber';if(/DA HA CANH|DA CAT CANH|ARRIVED|DEPARTED/.test(u))return'green';if(/LAM THU TUC|BOARDING|LEN TAU BAY/.test(u))return'blue';return''}
function isDelayed(r){const u=fold(sourceStatus(r));return /TRE|DELAY|DOI GIO|RESCHEDULED/.test(u)||(hhmm(r.estimatedTime)&&hhmm(r.estimatedTime)!==hhmm(r.scheduledTime))}
function withinBank(r,bank){if(bank==='all')return true;const h=Number((hhmm(r.scheduledTime)||'99:00').slice(0,2));const [a,b]=bank.split('-').map(Number);return h>=a&&h<b}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtEvent(e){if(e.type==='FIRST_SEEN')return 'Ghi nhận chuyến lần đầu trong JoTrip AutoSync.';const parts=[];for(const [field,c] of Object.entries(e.changes||{})){const names={estimatedTime:'ETA/ETD',actualTime:'Giờ thực tế',notesVn:'Trạng thái',gate:'Gate',belt:'Băng chuyền',parkingBay:'Bãi đỗ',scheduledTime:'Giờ lịch',boardingStart:'Boarding',boardingFinish:'Kết thúc boarding'};parts.push(`${names[field]||field}: ${c.from??'∅'} → ${c.to??'∅'}`)}return parts.join(' · ')||'Dữ liệu chuyến có thay đổi.'}
function eventTime(e){try{return new Date(e.at).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Ho_Chi_Minh'})}catch{return'--:--'}}

async function fetchJson(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function fetchEvents(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(r.status===404)return[];if(!r.ok)throw new Error(`events HTTP ${r.status}`);const text=await r.text();return text.split('\n').filter(Boolean).map(line=>{try{return JSON.parse(line)}catch{return null}}).filter(Boolean)}

async function load(){state.date=$('#historyDate').value||vnDate();$('#archiveHealth').className='archive-pill';$('#archiveHealth').textContent='ĐANG TẢI';$('#historyError').classList.add('hidden');try{const [raw,events]=await Promise.all([fetchJson(`${DATA_BASE}/raw/${state.date}.json`),fetchEvents(`${DATA_BASE}/history/${state.date}/events.jsonl`)]);state.raw=raw;state.events=events;$('#archiveHealth').className='archive-pill good';$('#archiveHealth').textContent=`RAW ${raw.collected_at_vn?.slice(11,16)||''} · ${events.length} EVENTS`;render()}catch(e){state.raw=null;state.events=[];$('#archiveHealth').className='archive-pill bad';$('#archiveHealth').textContent='CHƯA CÓ DATA';$('#historyError').textContent=`Chưa có dữ liệu archive cho ${state.date}.`;$('#historyError').classList.remove('hidden');render()}}

function allRows(){if(!state.raw)return[];return[...(state.raw.arrivals||[]).map(r=>({...r,_direction:'arrival'})),...(state.raw.departures||[]).map(r=>({...r,_direction:'departure'}))]}
function filteredRows(){let rows=allRows();if(state.direction!=='all')rows=rows.filter(r=>r._direction===state.direction);rows=rows.filter(r=>withinBank(r,state.time));if(state.query){const q=fold(state.query);rows=rows.filter(r=>fold([r.flightNo,r.airlineName,r.airline,r.cityName,r.route,r.country,sourceStatus(r)].join(' ')).includes(q))}rows.sort((a,b)=>(mins(a.scheduledTime)??9999)-(mins(b.scheduledTime)??9999));return rows}
function changedKeys(){return new Set(state.events.filter(e=>e.type==='CHANGED').map(e=>e.key))}
function renderMetrics(rows){const all=allRows(),changed=changedKeys();$('#hTotal').textContent=all.length||0;$('#hArrivals').textContent=all.filter(r=>r._direction==='arrival').length;$('#hDepartures').textContent=all.filter(r=>r._direction==='departure').length;$('#hChanged').textContent=changed.size;$('#hDelayed').textContent=all.filter(isDelayed).length;$('#historyCount').textContent=`${rows.length} chuyến phù hợp`;$('#historyTitle').textContent=`Dữ liệu ${state.date.split('-').reverse().join('/')}`}
function render(){const rows=filteredRows();renderMetrics(rows);if(!rows.length){$('#historyList').innerHTML='<div class="history-empty">Không có chuyến phù hợp bộ lọc hiện tại.</div>';return}const byKey=new Map();for(const e of state.events){if(!byKey.has(e.key))byKey.set(e.key,[]);byKey.get(e.key).push(e)}$('#historyList').innerHTML=rows.map((r,i)=>{const k=key(r._direction,r),events=byKey.get(k)||[],scheduled=hhmm(r.scheduledTime)||'--:--',estimated=hhmm(r.estimatedTime),actual=hhmm(r.actualTime),status=humanStatus(r),route=r.route||r.cityName||'',sub=[r.airlineName||r.airline,events.filter(e=>e.type==='CHANGED').length?`${events.filter(e=>e.type==='CHANGED').length} thay đổi`:null].filter(Boolean).join(' · ');const timeSub=actual?`Thực tế ${actual}`:estimated&&estimated!==scheduled?`Dự kiến ${estimated}`:(r._direction==='arrival'?'Đến PQC':'Rời PQC');const timeline=events.length?events.map(e=>`<div class="event-line"><span class="event-time">${escapeHtml(eventTime(e))}</span><span class="event-type">${escapeHtml(e.type==='FIRST_SEEN'?'FIRST SEEN':'CHANGED')}</span><span class="event-detail">${escapeHtml(fmtEvent(e))}</span></div>`).join(''):'<div class="event-line"><span></span><span></span><span class="event-detail">Chưa ghi nhận thay đổi sau khi bắt đầu lưu event history.</span></div>';return `<div class="history-row" data-row="${i}"><div class="history-row-main"><div class="h-flight">${escapeHtml(r.flightNo||'')}</div><div class="h-time">${escapeHtml(scheduled)}<small>${escapeHtml(timeSub)}</small></div><div class="h-route">${escapeHtml(route)}<small>${escapeHtml(sub)}</small></div><div class="h-type">${r._direction==='arrival'?'CHUYẾN ĐẾN':'CHUYẾN ĐI'}</div><div class="h-status ${statusClass(r)}">${escapeHtml(status)}</div><div class="h-chevron">›</div></div><div class="history-timeline">${timeline}</div></div>`}).join('');document.querySelectorAll('.history-row-main').forEach(el=>el.onclick=()=>el.parentElement.classList.toggle('open'))}

$('#historyDate').value=vnDate();
$('#historyDate').addEventListener('change',load);
$('#historyDirection').addEventListener('change',e=>{state.direction=e.target.value;render()});
$('#historyTime').addEventListener('change',e=>{state.time=e.target.value;render()});
$('#historySearch').addEventListener('input',e=>{state.query=e.target.value.trim();render()});
load();
