const DATA_BASE='https://raw.githubusercontent.com/kenzuko/Jotrip-Lab/data-weather/data/weather-nowcast';
const API_BASE='https://api.github.com/repos/kenzuko/Jotrip-Lab/contents/data/weather-nowcast';
const POINTS={an_thoi:'An Thới',duong_dong:'Dương Đông',ganh_dau:'Gành Dầu',rach_gia:'Rạch Giá'};
const LEVEL_ORDER={LOW:0,WATCH:1,ELEVATED:2,HIGH:3};
const $=s=>document.querySelector(s);
const state={catalog:null,query:'',point:'all',level:'all',summaryCache:new Map(),eventCache:new Map()};

function fold(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').toUpperCase().replace(/\s+/g,' ').trim()}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmt(v,d=1){const n=Number(v);return Number.isFinite(n)?Number(n.toFixed(d)).toString():'—'}
function dateVN(s){const p=String(s||'').split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:s||'—'}
function clock(s){try{return new Date(s).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Ho_Chi_Minh'})}catch{return'--:--'}}
function levelClass(v){return String(v||'').toLowerCase()}
function apiPath(url){return String(url).replace(DATA_BASE+'/','')}
function decodeBase64Utf8(value){const raw=atob(String(value||'').replace(/\s+/g,'')),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return new TextDecoder('utf-8').decode(bytes)}
async function fetchText(url){try{const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(r.ok)return r.text();throw new Error(`raw HTTP ${r.status}`)}catch(rawError){const path=apiPath(url),r=await fetch(`${API_BASE}/${path}?ref=data-weather&t=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw new Error(`${rawError.message}; api HTTP ${r.status}`);const meta=await r.json();if(meta.type!=='file'||!meta.content)throw new Error('GitHub API không trả file content');return decodeBase64Utf8(meta.content)}}
async function fetchJson(url){return JSON.parse(await fetchText(url))}
async function fetchEvents(date){if(state.eventCache.has(date))return state.eventCache.get(date);try{const text=await fetchText(`${DATA_BASE}/history/${date}/events.jsonl`),rows=text.split('\n').filter(Boolean).map(x=>{try{return JSON.parse(x)}catch{return null}}).filter(Boolean);state.eventCache.set(date,rows);return rows}catch(e){if(/404/.test(e.message)){state.eventCache.set(date,[]);return[]}throw e}}
async function summary(date){if(!date)return null;if(state.summaryCache.has(date))return state.summaryCache.get(date);const data=await fetchJson(`${DATA_BASE}/summary/${date}.json`);state.summaryCache.set(date,data);return data}

function matchingDates(){const rows=[...(state.catalog?.dates||[])];const q=fold(state.query);return rows.filter(r=>{if(state.point!=='all'&&!r.peak_levels?.[state.point])return false;if(state.level!=='all'){if(state.point==='all'){if(!Object.values(r.peak_levels||{}).includes(state.level))return false}else if(r.peak_levels?.[state.point]!==state.level)return false}if(q){const hay=fold([r.date,dateVN(r.date),...Object.entries(r.peak_levels||{}).flatMap(([k,v])=>[POINTS[k],v]),...Object.values(r.max_scores||{})].join(' '));if(!hay.includes(q))return false}return true}).sort((a,b)=>b.date.localeCompare(a.date))}
function renderArchive(){const rows=matchingDates();$('#archiveCount').textContent=`${rows.length} ngày`;if(!rows.length){$('#archiveList').innerHTML='<div class="empty">Không có ngày phù hợp bộ lọc.</div>';return}$('#archiveList').innerHTML=rows.map(r=>{const pills=Object.entries(r.peak_levels||{}).map(([k,v])=>`<span class="pill ${levelClass(v)}">${esc(POINTS[k])} · ${esc(v)} ${fmt(r.max_scores?.[k],0)}</span>`).join('');return `<article class="archive-row" data-date="${esc(r.date)}"><div class="archive-date">${esc(dateVN(r.date))}</div><div class="archive-meta"><span>${r.sample_count||0} mẫu</span><span>${r.material_event_count||0} thay đổi đáng kể</span><span>${esc(clock(r.first_sampled_time))} → ${esc(clock(r.last_sampled_time))}</span></div><div class="peak-pills">${pills}</div></article>`}).join('');document.querySelectorAll('.archive-row').forEach(el=>el.addEventListener('click',()=>{const d=el.dataset.date;$('#eventDate').value=d;$('#dateA').value=d;renderEvents();renderCompare()}))}

function setOptions(){const dates=(state.catalog?.dates||[]).map(x=>x.date).sort((a,b)=>b.localeCompare(a));const opts=dates.map(d=>`<option value="${d}">${dateVN(d)}</option>`).join('');for(const id of ['dateA','dateB','eventDate'])$(id).innerHTML=opts;if(dates.length){$('#dateA').value=dates[0];$('#eventDate').value=dates[0];$('#dateB').value=dates[1]||dates[0]}}
function metric(label,a,b,unit='',inverse=false){const av=Number(a),bv=Number(b),has=Number.isFinite(av)&&Number.isFinite(bv),delta=has?bv-av:null;let cls='neutral',sign='';if(delta!==null&&Math.abs(delta)>1e-9){const up=delta>0;cls=(up!==inverse)?'up':'down';sign=delta>0?'+':''}return `<div class="compare-card"><span>${esc(label)}</span><b>${fmt(b,1)}${unit}</b><small>A: ${fmt(a,1)}${unit}</small><div class="delta ${cls}">${delta===null?'Không đủ dữ liệu':`${sign}${fmt(delta,1)}${unit}`}</div></div>`}
function metricText(label,a,b){const ao=LEVEL_ORDER[a],bo=LEVEL_ORDER[b],delta=Number.isFinite(ao)&&Number.isFinite(bo)?bo-ao:null;const cls=delta===null||delta===0?'neutral':delta>0?'up':'down';return `<div class="compare-card"><span>${esc(label)}</span><b>${esc(b||'—')}</b><small>A: ${esc(a||'—')}</small><div class="delta ${cls}">${delta===null?'Không đủ dữ liệu':delta===0?'Không đổi':delta>0?'Mức cao hơn':'Mức thấp hơn'}</div></div>`}
async function renderCompare(){const a=$('#dateA').value,b=$('#dateB').value,p=$('#comparePoint').value;if(!a||!b)return;$('#compareState').textContent='ĐANG ĐỌC';try{const [sa,sb]=await Promise.all([summary(a),summary(b)]),pa=sa?.points?.[p]||{},pb=sb?.points?.[p]||{};$('#compareCards').innerHTML=[metricText('Mức cao nhất',pa.peak_level,pb.peak_level),metric('Score trung bình',pa.avg_score,pb.avg_score),metric('Score cao nhất',pa.max_score,pb.max_score),metric('Đỉnh mây lạnh nhất',pa.min_cold_cloud_top_temp_c,pb.min_cold_cloud_top_temp_c,' °C',true),metric('Đỉnh mây cao nhất',pa.max_high_cloud_top_height_m?pa.max_high_cloud_top_height_m/1000:null,pb.max_high_cloud_top_height_m?pb.max_high_cloud_top_height_m/1000:null,' km'),metric('Cooling mạnh nhất',pa.min_cooling_c_per_20m_proxy,pb.min_cooling_c_per_20m_proxy,' °C',true)].join('');const scoreA=Number(pa.avg_score),scoreB=Number(pb.avg_score),parts=[];if(Number.isFinite(scoreA)&&Number.isFinite(scoreB)){const d=scoreB-scoreA;if(Math.abs(d)<5)parts.push('Cường độ tín hiệu đối lưu trung bình khá tương đồng giữa hai ngày.');else parts.push(`Ngày B có score trung bình ${d>0?'cao hơn':'thấp hơn'} khoảng ${Math.abs(d).toFixed(0)} điểm so với ngày A.`)}if(pa.peak_level&&pb.peak_level&&pa.peak_level!==pb.peak_level)parts.push(`Mức cao nhất đổi từ ${pa.peak_level} sang ${pb.peak_level}.`);parts.push('So sánh này dựa trên summary tích lũy của mọi lần quan sát thành công, không cần lưu toàn bộ snapshot 30 phút.');$('#compareInsight').textContent=parts.join(' ');$('#compareState').textContent=`${POINTS[p]} · ${dateVN(a)} / ${dateVN(b)}`}catch(e){$('#compareCards').innerHTML='<div class="empty error">Không đọc được summary cho cặp ngày này.</div>';$('#compareInsight').textContent=e.message;$('#compareState').textContent='DATA ERROR'}}

function describeChanges(e){if(e.type==='FIRST_SEEN')return 'Bắt đầu ghi nhận trạng thái ngày.';const names={score:'score',level:'mức',cold_cloud_top_temp_c:'nhiệt độ đỉnh mây p05',high_cloud_top_height_m:'độ cao đỉnh mây p95',cooling_c_per_20m_proxy:'cooling ~20 phút',lightning_observed:'sét direct'};const chunks=[];for(const [k,v] of Object.entries(e.changes||{})){if(k==='first_seen')continue;const from=v?.from??'∅',to=v?.to??'∅';chunks.push(`${names[k]||k}: ${from} → ${to}`)}return chunks.join(' · ')||'Có thay đổi đáng kể.'}
async function renderEvents(){const date=$('#eventDate').value,p=$('#eventPoint').value;if(!date)return;$('#timelineMeta').textContent='ĐANG ĐỌC';try{let events=await fetchEvents(date);if(p!=='all')events=events.filter(e=>e.point===p);events.sort((a,b)=>String(b.sampled_time||b.at).localeCompare(String(a.sampled_time||a.at)));$('#timelineMeta').textContent=`${events.length} event · ${dateVN(date)}`;if(!events.length){$('#eventList').innerHTML='<div class="empty">Không có material event phù hợp.</div>';return}$('#eventList').innerHTML=events.map(e=>{const lvl=e.current?.level||e.changes?.level?.to||'WATCH';return `<article class="event ${levelClass(lvl)}"><time>${esc(clock(e.sampled_time||e.at))}</time><div class="event-point">${esc(POINTS[e.point]||e.point)} · ${esc(lvl)}</div><div class="event-detail"><b>${esc(e.type)}</b> · ${esc(describeChanges(e))}</div></article>`}).join('')}catch(e){$('#timelineMeta').textContent='DATA ERROR';$('#eventList').innerHTML=`<div class="empty error">${esc(e.message)}</div>`}}

async function load(){try{const catalog=await fetchJson(`${DATA_BASE}/catalog.json`);state.catalog=catalog;$('#archiveHealth').className='health-pill good';$('#archiveHealth').textContent=`DATA-WEATHER · ${catalog.dates?.length||0} NGÀY`;setOptions();renderArchive();await Promise.all([renderCompare(),renderEvents()])}catch(e){$('#archiveHealth').className='health-pill bad';$('#archiveHealth').textContent='ARCHIVE ERROR';$('#archiveList').innerHTML=`<div class="empty error">Không tải được catalog: ${esc(e.message)}</div>`}}

$('#historySearch').addEventListener('input',e=>{state.query=e.target.value;renderArchive()});
$('#pointFilter').addEventListener('change',e=>{state.point=e.target.value;renderArchive()});
$('#levelFilter').addEventListener('change',e=>{state.level=e.target.value;renderArchive()});
$('#dateA').addEventListener('change',renderCompare);$('#dateB').addEventListener('change',renderCompare);$('#comparePoint').addEventListener('change',renderCompare);$('#eventDate').addEventListener('change',renderEvents);$('#eventPoint').addEventListener('change',renderEvents);
load();
