(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=$$('.screen');
const loadScript=src=>new Promise((resolve,reject)=>{const old=document.querySelector(`script[data-lazy="${src}"]`);if(old){if(old.dataset.ready==='1')resolve();else old.addEventListener('load',resolve,{once:true});return}const s=document.createElement('script');s.src=src;s.async=true;s.dataset.lazy=src;s.onload=()=>{s.dataset.ready='1';resolve()};s.onerror=reject;document.head.appendChild(s)});
let muted=false,ac=null,engineOsc=null,engineGain=null;
function audio(){if(muted)return null;try{if(!ac)ac=new (window.AudioContext||window.webkitAudioContext)();if(ac.state==='suspended')ac.resume();return ac}catch{return null}}
function beep(f=600,d=.05,v=.018,type='square'){const a=audio();if(!a)return;const o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=f;g.gain.value=v;g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}
function engineStart(){const a=audio();if(!a)return;engineStop();engineOsc=a.createOscillator();engineGain=a.createGain();engineOsc.type='sawtooth';engineOsc.frequency.value=78;engineGain.gain.value=.009;engineOsc.connect(engineGain).connect(a.destination);engineOsc.start()}
function engineStop(){try{engineOsc&&engineOsc.stop()}catch{}engineOsc=null;engineGain=null}
$('#soundBtn').onclick=()=>{muted=!muted;$('#soundBtn').textContent=muted?'SOUND OFF':'SOUND ON';if(muted)engineStop();else beep(620,.04,.012)};
const show=id=>{screens.forEach(s=>s.classList.toggle('active',s.id===id));if(id==='airport')loadAirport();if(id==='characters')buildCharacters();if(id==='map')syncMap();};
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>{beep(520,.035,.012);show(b.dataset.go)}));
const island=(window.A&&window.A.map)||'';$('#landingIsland').src=island;$('#mapIsland').src=island;
let bridgeReady=null;const loadBridge=()=>bridgeReady||(bridgeReady=loadScript('./asset-bridge.js?v=fast4'));
let airportLoaded=false;
async function loadAirport(){if(airportLoaded)return;airportLoaded=true;try{await loadBridge();const o=window.PQ_ASSETS||{};$('#airportBg').style.backgroundImage=`url(${o['airport-scene']||''})`;$('#ken').src=o['ken-wave']||'';}catch(e){console.error('airport assets',e)}}
const roster=[['THE TRAVELER','Ready for anything.','traveler'],['THE EXPLORER',"Let's see what's out there.",'explorer'],['THE UNCLE','I packed snacks.','uncle'],['THE GRANDMA','No need to rush.','grandma'],['THE KID','Can we go now?','kid'],['THE OLD FISHERMAN','I know these waters.','fisherman'],['PHU QUOC RIDGEBACK','No ticket needed.','ridgeback'],['PEPPER','A little spicy.','pepper']];
let selected=0,charsBuilt=false,charsLoading=false;
async function buildCharacters(){if(charsBuilt||charsLoading)return;charsLoading=true;try{await loadBridge();const assets=window.PQ_ASSETS||{},grid=$('#characterGrid');roster.forEach((c,i)=>{const b=document.createElement('button');b.className='character-card'+(i===0?' selected':'');const im=document.createElement('img');im.alt=c[0];im.decoding='async';im.src=assets['char-'+c[2]]||'';const l=document.createElement('div');l.className='char-label';l.innerHTML=`<b>${c[0]}</b><small>${c[1]}</small>`;b.append(im,l);b.onclick=()=>{beep(560,.03,.012);selected=i;[...grid.children].forEach((x,j)=>x.classList.toggle('selected',j===i))};grid.appendChild(b)});charsBuilt=true;}catch(e){console.error('character assets',e)}finally{charsLoading=false}}
const state={jo:+localStorage.getItem('pq_jo')||0,best:+localStorage.getItem('pq_best')||0,piece:localStorage.getItem('pq_sunset_piece')==='1'};
function syncMap(){const n=$('#playerName').value.trim()||'Traveler';$('#mapHello').textContent=`WELCOME, ${n.toUpperCase()}`;$('#mapJo').textContent=state.jo;$('#mapPieces').textContent=(state.piece?1:0)+'/1';$('#sunsetState').textContent=state.piece?'ENDLESS READY':'PLAY NOW'}
$('#openMapBtn').onclick=()=>{beep(520,.035,.012);syncMap();show('map')};
const canvas=$('#gameCanvas'),ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=false;
const imgs={};let gameAssetsReady=false,gameAssetsLoading=false;
function setModal(id){['loadGame','tutorial','gameOver','clear'].forEach(x=>$('#'+x).classList.toggle('show',x===id))}
function imgFrom(src){const im=new Image();im.decoding='async';im.src=src||'';return im}
async function loadGameAssets(){if(gameAssetsReady)return;if(gameAssetsLoading)return;gameAssetsLoading=true;setModal('loadGame');const scripts=['./runtime/asset-bg.js?v=fast4','./runtime/asset-rides.js?v=fast4','./runtime/asset-props.js?v=fast4'];for(let i=0;i<scripts.length;i++){await loadScript(scripts[i]);$('#loadText').textContent=Math.round((i+1)/scripts.length*70)+'%'}const A=window.A||{};const srcs={bg:A.bg,ride1:A.ride1,ride2:A.ride2,ride3:A.ride3,ride4:A.ride4||A.ride1,planter:A.planter,chair:A.chair,table:A.table,menu:A.menu,tripod:A.tripod,suitcase:A.suitcase,coin1:A.coin,coin2:A.coin,coin3:A.coin,coin4:A.coin};const entries=Object.entries(srcs);let done=0;await Promise.all(entries.map(([k,src])=>new Promise(res=>{const im=imgFrom(src);imgs[k]=im;const fin=()=>{done++;$('#loadText').textContent=(70+Math.round(done/entries.length*30))+'%';res()};if(im.complete)fin();else{im.onload=fin;im.onerror=fin}})));$('#gameAmbient').style.backgroundImage=`url(${A.bg||''})`;gameAssetsReady=true;gameAssetsLoading=false;drawIdle();setModal('tutorial')}
$('#sunsetPin').onclick=async()=>{beep(520,.035,.012);show('game');await loadGameAssets()};
$$('.backMap').forEach(b=>b.onclick=()=>{stop();syncMap();show('map')});
const W=540,H=960,GROUND=806,P={x:90,w:120,h:132};
const defs=[{k:'planter',w:70,h:66,hit:43},{k:'chair',w:58,h:72,hit:34},{k:'table',w:76,h:61,hit:44},{k:'menu',w:62,h:79,hit:39},{k:'tripod',w:65,h:80,hit:34},{k:'suitcase',w:52,h:64,hit:34}];
let run=false,raf=0,last=0,score=0,runJo=0,world=0,py=0,vy=0,onGround=true,frame=0,frameClock=0,obs=[],coin=null,trainingLeft=2,toast='',toastUntil=0,shake=0,dust=[],endless=false,clearing=false;
function difficulty(){if(score<5)return{speed:330,gap:[360,430]};if(score<15)return{speed:370,gap:[325,395]};if(score<35)return{speed:410,gap:[292,350]};if(score<60)return{speed:450,gap:[260,320]};return{speed:485+Math.min(55,(score-60)*1.25),gap:[230,290]}}
function spawnObstacle(initial=false){const d=difficulty(),pool=score<8?defs.slice(0,4):defs,def=pool[Math.floor(Math.random()*pool.length)],x=initial?W+210:W+d.gap[0]+Math.random()*(d.gap[1]-d.gap[0]);obs.push({...def,x,y:GROUND-def.h,passed:false,training:trainingLeft>0});if(trainingLeft>0)trainingLeft--}
function spawnCoin(){coin={x:W+250+Math.random()*260,y:620+Math.random()*95,w:44,h:44,frame:0}}
function hop(auto=false){if(!run||!onGround)return;vy=-710;onGround=false;if(!auto)beep(620,.045,.018)}
function say(t,ms=650){toast=t;toastUntil=performance.now()+ms}
function start(mode='normal'){if(!gameAssetsReady)return;setModal('');score=0;runJo=0;world=0;py=0;vy=0;onGround=true;frame=0;frameClock=0;obs=[];coin=null;trainingLeft=2;toast='';shake=0;dust=[];endless=mode==='endless';clearing=false;spawnObstacle(true);spawnCoin();run=true;last=performance.now();engineStart();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop)}
function stop(){run=false;cancelAnimationFrame(raf);engineStop()}
function gameOver(){stop();state.best=Math.max(state.best,score);state.jo+=runJo;localStorage.setItem('pq_best',state.best);localStorage.setItem('pq_jo',state.jo);$('#gameOverText').innerHTML=`SCORE <b>${score}</b> · JO <b>+${runJo}</b><br><small>Tap earlier and keep the rhythm.</small>`;beep(160,.18,.04,'sawtooth');setModal('gameOver')}
function clearGame(){if(clearing||endless)return;clearing=true;stop();state.best=Math.max(state.best,100);state.jo+=runJo;state.piece=true;localStorage.setItem('pq_best',state.best);localStorage.setItem('pq_jo',state.jo);localStorage.setItem('pq_sunset_piece','1');beep(1040,.08,.025);setTimeout(()=>beep(1320,.1,.025),90);setModal('clear')}
function loop(t){if(!run)return;const dt=Math.min(.034,(t-last)/1000);last=t;const d=difficulty();world+=d.speed*dt;frameClock+=dt;if(frameClock>.075){frameClock=0;frame=(frame+1)%4}if(engineOsc&&ac)engineOsc.frequency.setTargetAtTime(78+Math.min(35,score*.65),ac.currentTime,.04);if(!onGround){vy+=2250*dt;py+=vy*dt;if(py>=0){py=0;vy=0;onGround=true;shake=4;beep(220,.025,.008)}}obs.forEach(o=>o.x-=d.speed*dt);if(coin)coin.x-=d.speed*.97*dt;for(const o of obs){if(!o.passed&&o.x+o.w<P.x){o.passed=true;score++;if(score===1)say("THAT'S IT.");if(score===5)say('NOW WE RIDE.');if(score===25)say('FASTER!');if(score===69)say('NICE.',950);spawnObstacle(false);if(score===100&&!endless){draw(t);clearGame();return}}}obs=obs.filter(o=>o.x>-180);if(coin&&coin.x<-70)spawnCoin();const pl=P.x+24,pr=P.x+P.w-15,pb=GROUND+py,pt=pb-P.h;for(const o of obs){const ol=o.x+(o.w-o.hit)/2,orr=ol+o.hit,ot=o.y+8;if(pr>ol&&pl<orr&&pb>ot&&pt<GROUND){if(o.training){o.training=false;say('HOP EARLIER!',850);hop(true);o.x+=130;beep(420,.08,.02)}else{draw(t);gameOver();return}}}if(coin&&pr>coin.x&&pl<coin.x+coin.w&&pt<coin.y+coin.h&&pb>coin.y){runJo++;say('+1 JO',420);beep(1180,.055,.023);spawnCoin()}if(Math.random()<.28)dust.push({x:P.x+25,y:GROUND-4,a:.65,vx:-90-Math.random()*70,vy:-15-Math.random()*18});dust.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.a-=dt*1.7});dust=dust.filter(p=>p.a>0);shake*=.82;draw(t);raf=requestAnimationFrame(loop)}
function cover(im,x,y,w,h){if(!im||!im.complete||!im.naturalWidth){ctx.fillStyle='#0b6686';ctx.fillRect(x,y,w,h);return}const r=Math.max(w/im.naturalWidth,h/im.naturalHeight),sw=w/r,sh=h/r,sx=(im.naturalWidth-sw)/2,sy=(im.naturalHeight-sh)/2;ctx.drawImage(im,sx,sy,sw,sh,x,y,w,h)}
function draw(now=performance.now()){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);cover(imgs.bg,0,0,W,H);const d=difficulty(),roadY=GROUND+8;ctx.fillStyle='rgba(55,42,31,.96)';ctx.fillRect(0,roadY,W,H-roadY);for(let x=-(world*1.5%96)-96;x<W+96;x+=96){ctx.fillStyle='rgba(210,185,145,.26)';ctx.fillRect(x,roadY+34,51,5);ctx.fillStyle='rgba(22,15,10,.32)';ctx.fillRect(x+58,roadY+34,30,5)}for(const p of dust){ctx.globalAlpha=Math.max(0,p.a);ctx.fillStyle='#e4c79e';ctx.beginPath();ctx.arc(p.x,p.y,3+(1-p.a)*4,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const o of obs){const im=imgs[o.k];if(im&&im.complete)ctx.drawImage(im,o.x,o.y,o.w,o.h)}if(coin){coin.frame=((now/80)|0)%4;const im=imgs['coin'+(coin.frame+1)];if(im&&im.complete)ctx.drawImage(im,coin.x,coin.y,coin.w,coin.h)}const y=GROUND+py;ctx.fillStyle='rgba(0,0,0,.42)';const lift=Math.min(1,Math.abs(py)/130);ctx.beginPath();ctx.ellipse(P.x+61,GROUND+6,51*(1-lift*.45),9*(1-lift*.6),0,0,Math.PI*2);ctx.fill();const rim=imgs['ride'+(frame+1)];if(rim&&rim.complete){ctx.save();ctx.translate(P.x+P.w/2,y);ctx.rotate(onGround?Math.sin(world/18)*.014:Math.max(-.10,Math.min(.08,vy/7000)));ctx.drawImage(rim,-P.w/2,-P.h,P.w,P.h);ctx.restore()}ctx.textBaseline='top';ctx.shadowColor='rgba(0,0,0,.8)';ctx.shadowOffsetX=2;ctx.shadowOffsetY=2;ctx.font='900 18px monospace';ctx.fillStyle='#fff';ctx.fillText(`SCORE ${score}`,18,22);ctx.textAlign='center';ctx.fillText(`JO ${runJo}`,270,22);ctx.textAlign='right';ctx.fillText(`BEST ${state.best}`,522,22);ctx.textAlign='center';ctx.shadowOffsetX=0;ctx.shadowOffsetY=0;ctx.fillStyle='#f7b72d';ctx.font='900 13px monospace';ctx.fillText('SUNSET TOWN',270,82);ctx.fillStyle='#fff';ctx.font='900 30px monospace';ctx.fillText('NO BRAKES',270,103);ctx.font='11px monospace';ctx.fillText('TAP · CLICK · SPACE',270,145);ctx.font='10px monospace';ctx.fillStyle='rgba(255,255,255,.84)';ctx.fillText(`${d.speed|0} PX/S · ${score<2?'TRAINING':endless?'ENDLESS':'NO BRAKES'}`,270,918);if(now<toastUntil){ctx.font='900 22px monospace';ctx.fillStyle='#f7b72d';ctx.fillText(toast,270,205)}ctx.textAlign='left';ctx.shadowColor='transparent';ctx.restore()}
function drawIdle(){if(!gameAssetsReady){ctx.fillStyle='#08344a';ctx.fillRect(0,0,W,H);return}if(!obs.length)obs=[{...defs[0],x:650,y:GROUND-defs[0].h,passed:false,training:true}];if(!coin)coin={x:430,y:660,w:44,h:44,frame:0};draw()}
$('#startRide').onclick=()=>{beep(520,.035,.012);start()};$('#retry').onclick=()=>{beep(520,.035,.012);start()};$('#endless').onclick=()=>{beep(620,.045,.015);start('endless')};canvas.addEventListener('pointerdown',()=>hop());window.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();hop()}});window.addEventListener('pagehide',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden&&run)stop()});syncMap();
})();