import fs from 'node:fs/promises';
const src='weather/research/ground-truth-probe/vrain-public.json';
const callsDst='weather/research/ground-truth-probe/vrain-calls.json';
const routesDst='weather/research/ground-truth-probe/vrain-routes.json';
const raw=JSON.parse(await fs.readFile(src,'utf8'));
const tx=(raw.transactions||[]).filter(x=>x.resource_type!=='document');
const calls={generated_at:new Date().toISOString(),source_generated_at:raw.generated_at,final_url:raw.final_url,calls:tx.map(x=>({url:x.url,status:x.status,method:x.method,resource_type:x.resource_type,content_type:x.content_type,post_data:x.post_data,body_length:x.body_length,body_preview:x.body_preview}))};
const routes={generated_at:calls.generated_at,source_generated_at:raw.generated_at,routes:tx.map(x=>({url:x.url,status:x.status,method:x.method,resource_type:x.resource_type,content_type:x.content_type,body_length:x.body_length}))};
await fs.writeFile(callsDst,JSON.stringify(calls,null,2)+'\n');
await fs.writeFile(routesDst,JSON.stringify(routes,null,2)+'\n');
console.log(JSON.stringify(routes,null,2));
