(()=>{
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const liveUrl=()=>String(window.JOTRIP_LIVE_API_URL||'').replace(/\/$/,'');
function airline(r){return r?.airline_name||r?.airline||r?.airline_code||'Chưa rõ hãng'}
function score(records){const m=new Map();for(const r of records||[]){const d=Number(r?.actual_delay_minutes);if(!r?.actual_time||!Number.isFinite(d))continue;const name=airline(r),k=name.toUpperCase();if(!m.has(k))m.set(k,{name,total:0,on:0,late:0,delaySum:0});const a=m.get(k);a.total++;if(d<=15)a.on++;else a.late++;a.delaySum+=Math.max(0,d)}return[...m.values()].sort((a,b)=>b.total-a.total||b.on-a.on)}
function render(records){const body=$('#airlinePerformanceBody');if(!body)return;const rows=score(records);body.innerHTML=rows.length?rows.map(a=>{const onPct=a.total?a.on*100/a.total:0,latePct=a.total?a.late*100/a.total:0,avg=a.total?a.delaySum/a.total:0;return `<tr><td><strong>${esc(a.name)}</strong></td><td>${a.total}</td><td>${a.on}</td><td>${a.late}</td><td class="rate-good">${onPct.toFixed(1)}%</td><td class="rate-watch">${latePct.toFixed(1)}%</td><td>${Math.round(avg)} phút</td></tr>`}).join(''):'<tr><td colspan="7">Chưa đủ chuyến có giờ thực tế để tính OTP15.</td></tr>';const total=rows.reduce((n,a)=>n+a.total,0),on=rows.reduce((n,a)=>n+a.on,0),late=rows.reduce((n,a)=>n+a.late,0);$('#airlineOnTimeRate').textContent=total?(on*100/total).toFixed(1)+'%':'-';$('#airlineDelayRate').textContent=total?(late*100/total).toFixed(1)+'%':'-'}
async function load(){try{const base=liveUrl();if(!base)return;const u=new URL(base);if(window.JOTRIP_BOARD_DATE)u.searchParams.set('date',window.JOTRIP_BOARD_DATE);u.searchParams.set('t',Date.now());const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const p=await r.json();render(p?.latest?.records||[])}catch(e){console.warn('Airline analytics unavailable',e)}}
window.addEventListener('jotrip:board-date',load);load();setInterval(load,60000);
})();
