const DATA_BASE='https://raw.githubusercontent.com/kenzuko/Jotrip-Lab/data-sunairport/data/sunairport';
const $=s=>document.querySelector(s);
const state={days:[],direction:'all',time:'all',airline:'all',query:''};
function vnDate(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const o={};p.forEach(x=>o[x.type]=x.value);return `${o.year}-${o.month}-${o.day}`}
function fold(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').toUpperCase().replace(/\s+/g,' ').trim()}
function hhmm(v){const m=String(v??'').match(/^(\d{2})(\d{2})/);return m?`${m[1]}:${m[2]}`:String(v||'').match(/^\d{1,2}:\d{2}$/)?.[0]||null}
function mins(v){const t=hhmm(v);if(!t)return null;const [h,m]=t.split(':').map(Number);return h*60+m}
function diff(a,b){const x=mins(a),y=mins(b);if(x==null||y==null)return null;let d=y-x;if(d<0)d+=1440;return d>=0&&d<=720?d:null}
function signedDiff(a,b){const x=mins(a),y=mins(b);if(x==null||y==null)return null;let d=y-x;if(d>720)d-=1440;if(d<-720)d+=1440;return d}
function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function sourceStatus(r){return String(r.notesVn||r.notesEn||r.status||r.remarks||'').trim()}
function airline(r){return r.airlineName||r.airline||r.airlineCode||'Chưa rõ hãng'}
function checkinTime(text){const m=String(text||'').match(/LÀM THỦ TỤC LÚC\s*(\d{1,2}:\d{2})/i);return m?m[1]:null}
function delayed(r){const u=fold(sourceStatus(r));if(/TRE|DELAY|DOI GIO|RESCHEDULED|POSTPONED|HOAN/.test(u))return true;const s=hhmm(r.scheduledTime),e=hhmm(r.estimatedTime);return !!(s&&e&&s!==e&&diff(s,e)>0)}
function cancelled(r){return /HUY|CANCEL/.test(fold(sourceStatus(r)))}
function delayMin(r){return delayed(r)?diff(hhmm(r.scheduledTime),hhmm(r.estimatedTime)):0}
function actualDelay(r){return hhmm(r.actualTime)?signedDiff(hhmm(r.scheduledTime),hhmm(r.actualTime)):null}
function humanStatus(r){const raw=sourceStatus(r),u=fold(raw),ci=checkinTime(raw);if(ci)return `Check-in từ ${ci}`;if(u.includes('DANG LAM THU TUC'))return 'Đang check-in';if(u.includes('QUAY THU TUC DA DONG'))return 'Check-in đã đóng';if(u.includes('CUA KHOI HANH DA DONG'))return 'Cửa khởi hành đã đóng';if(u.includes('HANH KHACH DANG LEN TAU BAY')||u.includes('BOARDING'))return 'Đang lên máy bay';if(u.includes('DA HA CANH')||u.includes('ARRIVED'))return 'Đã hạ cánh';if(u.includes('DA CAT CANH')||u.includes('DEPARTED'))return 'Đã cất cánh';if(cancelled(r))return 'Đã hủy';if(delayed(r)){const d=delayMin(r);return d>0?`Trễ ${d} phút`:'Trễ / đổi giờ'}return raw||'Đúng giờ / chưa ghi nhận trễ'}
function statusClass(r){if(cancelled(r))return'red';if(delayed(r))return'amber';const u=fold(sourceStatus(r));if(/DA HA CANH|DA CAT CANH|ARRIVED|DEPARTED/.test(u))return'green';if(/LAM THU TUC|BOARDING|LEN TAU BAY/.test(u))return'blue';return''}
function withinBank(r,bank){if(bank==='all')return true;const h=Number((hhmm(r.scheduledTime)||'99:00').slice(0,2));const [a,b]=bank.split('-').map(Number);return h>=a&&h<b}
function dateList(a,b){const out=[];let d=new Date(a+'T00:00:00Z'),end=new Date(b+'T00:00:00Z');while(d<=end&&out.length<31){out.push(d.toISOString().slice(0,10));d=new Date(d.getTime()+86400000)}return out}
async function fetchJson(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
async function fetchEvents(url){const r=await fetch(`${url}?t=${Date.now()}`,{cache:'no-store'});if(r.status===404)return[];if(!r.ok)return[];const text=await r.text();return text.split('\n').filter(Boolean).map(x=>{try{return JSON.parse(x)}catch{return null}}).filter(Boolean)}
function key(direction,row){return row?.id!=null?`${direction}|id:${row.id}`:`${direction}|${fold(row?.flightNo)}|${row?.scheduledTime||''}|${fold(row?.cityName)}`}
function fmtEvent(e){if(e.type==='FIRST_SEEN')return 'Ghi nhận chuyến lần đầu trong JoTrip AutoSync.';const names={estimatedTime:'ETA/ETD',actualTime:'Giờ thực tế',notesVn:'Trạng thái',gate:'Gate',belt:'Băng chuyền',parkingBay:'Bãi đỗ',scheduledTime:'Giờ lịch',boardingStart:'Boarding',boardingFinish:'Kết thúc boarding'};return Object.entries(e.changes||{}).map(([f,c])=>`${names[f]||f}: ${c.from??'∅'} → ${c.to??'∅'}`).join(' · ')||'Dữ liệu chuyến có thay đổi.'}
function eventTime(e){try{return new Date(e.at).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Ho_Chi_Minh'})}catch{return'--:--'}}
async function load(){let from=$('#historyFrom').value||vnDate(),to=$('#historyTo').value||from;if(to<from)[from,to]=[to,from];$('#historyFrom').value=from;$('#historyTo').value=to;const dates=dateList(from,to);$('#archiveHealth').className='archive-pill';$('#archiveHealth').textContent='ĐANG TẢI';$('#historyError').classList.add('hidden');try{const days=await Promise.all(dates.map(async date=>{try{const [raw,events]=await Promise.all([fetchJson(`${DATA_BASE}/raw/${date}.json`),fetchEvents(`${DATA_BASE}/history/${date}/events.jsonl`)]);return{date,raw,events}}catch{return null}}));state.days=days.filter(Boolean);if(!state.days.length)throw new Error('no data');$('#archiveHealth').className='archive-pill good';$('#archiveHealth').textContent=`${state.days.length} NGÀY · ${allRows().length} CHUYẾN`;refreshAirlines();render()}catch(e){state.days=[];$('#archiveHealth').className='archive-pill bad';$('#archiveHealth').textContent='CHƯA CÓ DATA';$('#historyError').textContent=`Chưa có dữ liệu archive trong khoảng ${from} - ${to}.`;$('#historyError').classList.remove('hidden');render()}}
function allRows(){const rows=[];for(const d of state.days){for(const r of d.raw?.arrivals||[])rows.push({...r,_direction:'arrival',_date:d.date,_events:d.events||[]});for(const r of d.raw?.departures||[])rows.push({...r,_direction:'departure',_date:d.date,_events:d.events||[]})}return rows}
function filteredRows(){let rows=allRows();if(state.direction!=='all')rows=rows.filter(r=>r._direction===state.direction);if(state.airline!=='all')rows=rows.filter(r=>fold(airline(r))===state.airline);rows=rows.filter(r=>withinBank(r,state.time));if(state.query){const q=fold(state.query);rows=rows.filter(r=>fold([r.flightNo,airline(r),r.cityName,r.route,r.country,sourceStatus(r)].join(' ')).includes(q))}rows.sort((a,b)=>a._date.localeCompare(b._date)||(mins(a.scheduledTime)??9999)-(mins(b.scheduledTime)??9999));return rows}
function refreshAirlines(){const sel=$('#historyAirline'),current=state.airline;const names=[...new Set(allRows().map(airline).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'vi'));sel.innerHTML='<option value="all">Tất cả hãng</option>'+names.map(n=>`<option value="${esc(fold(n))}">${esc(n)}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current;else state.airline='all'}
function airlineStats(rows){const m=new Map();for(const r of rows){const d=actualDelay(r);if(d==null||cancelled(r))continue;const n=airline(r),k=fold(n);if(!m.has(k))m.set(k,{name:n,total:0,on:0,late:0,sum:0});const a=m.get(k);a.total++;if(d<=15)a.on++;else a.late++;a.sum+=Math.max(0,d)}return [...m.values()].sort((a,b)=>b.total-a.total||b.on-a.on)}
function renderMetrics(rows){const all=filteredRows(),scored=all.map(r=>({r,d:actualDelay(r)})).filter(x=>x.d!=null&&!cancelled(x.r)),on=scored.filter(x=>x.d<=15),late=scored.filter(x=>x.d>15),avg=scored.map(x=>Math.max(0,x.d));$('#hTotal').textContent=all.length;$('#hArrivals').textContent=all.filter(r=>r._direction==='arrival').length;$('#hDepartures').textContent=all.filter(r=>r._direction==='departure').length;$('#hOnTime').textContent=on.length;$('#hDelayed').textContent=late.length;$('#hOnTimeRate').textContent=scored.length?(on.length*100/scored.length).toFixed(1)+'%':'-';$('#hAvgDelay').textContent=avg.length?Math.round(avg.reduce((a,b)=>a+b,0)/avg.length)+'p':'-';$('#historyCount').textContent=`${rows.length} chuyến phù hợp · ${scored.length} chuyến đã có giờ thực tế`;const f=$('#historyFrom').value,t=$('#historyTo').value;$('#historyTitle').textContent=f===t?`Dữ liệu ${f.split('-').reverse().join('/')}`:`Dữ liệu ${f.split('-').reverse().join('/')} - ${t.split('-').reverse().join('/')}`;const body=$('#historyAirlineBody');body.innerHTML=airlineStats(all).map(a=>{const op=a.total?a.on*100/a.total:0,lp=a.total?a.late*100/a.total:0,av=a.total?a.sum/a.total:0;return `<tr><td><strong>${esc(a.name)}</strong></td><td>${a.total}</td><td>${a.on}</td><td>${a.late}</td><td class="rate-good">${op.toFixed(1)}%</td><td class="rate-watch">${lp.toFixed(1)}%</td><td>${Math.round(av)} phút</td></tr>`}).join('')||'<tr><td colspan="7">Chưa đủ chuyến có giờ thực tế để tính OTP15.</td></tr>'}
function render(){const rows=filteredRows();renderMetrics(rows);if(!rows.length){$('#historyList').innerHTML='<div class="history-empty">Không có chuyến phù hợp bộ lọc hiện tại.</div>';return}$('#historyList').innerHTML=rows.map(r=>{const events=(r._events||[]).filter(e=>e.key===key(r._direction,r)),scheduled=hhmm(r.scheduledTime)||'--:--',estimated=hhmm(r.estimatedTime),actual=hhmm(r.actualTime),status=humanStatus(r),route=r.route||r.cityName||'',changed=events.filter(e=>e.type==='CHANGED').length,sub=[airline(r),r._date,changed?`${changed} thay đổi`:null].filter(Boolean).join(' · '),timeSub=actual?`Thực tế ${actual}`:estimated&&estimated!==scheduled?`Dự kiến ${estimated}`:(r._direction==='arrival'?'Đến PQC':'Rời PQC'),timeline=events.length?events.map(e=>`<div class="event-line"><span class="event-time">${esc(eventTime(e))}</span><span class="event-type">${esc(e.type==='FIRST_SEEN'?'FIRST SEEN':'CHANGED')}</span><span class="event-detail">${esc(fmtEvent(e))}</span></div>`).join(''):'<div class="event-line"><span></span><span></span><span class="event-detail">Chưa ghi nhận thay đổi trong event history.</span></div>';return `<div class="history-row"><div class="history-row-main"><div class="h-flight">${esc(r.flightNo||'')}</div><div class="h-time">${esc(scheduled)}<small>${esc(timeSub)}</small></div><div class="h-route">${esc(route)}<small>${esc(sub)}</small></div><div class="h-type">${r._direction==='arrival'?'CHUYẾN ĐẾN':'CHUYẾN ĐI'}</div><div class="h-status ${statusClass(r)}">${esc(status)}</div><div class="h-chevron">›</div></div><div class="history-timeline">${timeline}</div></div>`}).join('');document.querySelectorAll('.history-row-main').forEach(el=>el.onclick=()=>el.parentElement.classList.toggle('open'))}
const today=vnDate();$('#historyFrom').value=today;$('#historyTo').value=today;
$('#historyFrom').addEventListener('change',load);$('#historyTo').addEventListener('change',load);$('#historyDirection').addEventListener('change',e=>{state.direction=e.target.value;render()});$('#historyTime').addEventListener('change',e=>{state.time=e.target.value;render()});$('#historyAirline').addEventListener('change',e=>{state.airline=e.target.value;render()});$('#historySearch').addEventListener('input',e=>{state.query=e.target.value.trim();render()});
load();
