PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS runs (run_id TEXT PRIMARY KEY, report_date TEXT NOT NULL, collector_started_at TEXT NOT NULL, cutoff_at TEXT NOT NULL, synthesis_started_at TEXT, published_at TEXT, status TEXT NOT NULL CHECK(status IN ('collecting','cutoff','synthesizing','published','failed')), spec_version TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sources (source_id TEXT PRIMARY KEY, source_family TEXT NOT NULL, platform TEXT NOT NULL, market TEXT, language TEXT, access_class TEXT NOT NULL DEFAULT 'public');
CREATE TABLE IF NOT EXISTS query_registry (query_id TEXT PRIMARY KEY, market TEXT NOT NULL, language TEXT NOT NULL, source_family TEXT NOT NULL, query_text TEXT NOT NULL, query_mode TEXT NOT NULL CHECK(query_mode IN ('fixed','discovery')), active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS source_items (item_id TEXT PRIMARY KEY, source_id TEXT NOT NULL REFERENCES sources(source_id), source_native_id TEXT, canonical_url TEXT NOT NULL, published_at TEXT, observed_first_at TEXT NOT NULL, observed_last_at TEXT NOT NULL, content_hash TEXT, verification_status TEXT NOT NULL CHECK(verification_status IN ('verified','discovery_only','unverified','rejected')), UNIQUE(source_id, source_native_id), UNIQUE(canonical_url));
CREATE TABLE IF NOT EXISTS traveller_cases (case_id TEXT PRIMARY KEY, case_key TEXT NOT NULL UNIQUE, market TEXT, language TEXT, cohort TEXT, traveller_hash TEXT, first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS case_events (event_id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES traveller_cases(case_id), item_id TEXT NOT NULL REFERENCES source_items(item_id), observed_at TEXT NOT NULL, decision_stage INTEGER CHECK(decision_stage BETWEEN 1 AND 10), event_type TEXT NOT NULL, outcome TEXT, UNIQUE(case_id,item_id,event_type,observed_at));
CREATE TABLE IF NOT EXISTS observations (observation_id TEXT PRIMARY KEY, run_id TEXT NOT NULL REFERENCES runs(run_id), case_id TEXT REFERENCES traveller_cases(case_id), item_id TEXT NOT NULL REFERENCES source_items(item_id), evidence_label TEXT NOT NULL, evidence_strength TEXT NOT NULL, decision_stage INTEGER CHECK(decision_stage BETWEEN 1 AND 10), property_name TEXT, planned_los REAL, actual_los REAL, want TEXT, barrier TEXT, hidden_anxiety TEXT, competitor TEXT, orientation TEXT CHECK(orientation IN ('property-led','destination-led','unknown') OR orientation IS NULL), off_property_propensity TEXT, outcome TEXT, evidence_span TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS signals (signal_id TEXT PRIMARY KEY, name_vi TEXT NOT NULL, status TEXT NOT NULL CHECK(status IN ('MỚI','THEO DÕI','ĐÃ CÓ CƠ SỞ','ĐANG HẠ NHIỆT','LƯU TRỮ')), first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS signal_evidence (signal_id TEXT NOT NULL REFERENCES signals(signal_id), observation_id TEXT NOT NULL REFERENCES observations(observation_id), direction TEXT NOT NULL CHECK(direction IN ('support','counter')), PRIMARY KEY(signal_id,observation_id));
CREATE TABLE IF NOT EXISTS coverage (run_id TEXT NOT NULL REFERENCES runs(run_id), market TEXT NOT NULL, source_family TEXT NOT NULL, collector_status TEXT NOT NULL CHECK(collector_status IN ('OK','LIMITED','BLOCKED','PARSER_ERROR','NO_ELIGIBLE_ITEM','NOT_SCANNED')), candidates_seen INTEGER, origins_opened INTEGER, verified_items INTEGER, notes TEXT, PRIMARY KEY(run_id,market,source_family));
CREATE TABLE IF NOT EXISTS jotrip_leads (lead_id TEXT PRIMARY KEY, created_at TEXT NOT NULL, market TEXT, first_or_repeat TEXT, travel_date TEXT, nights INTEGER, party_size INTEGER, trip_type TEXT, property_name TEXT, product_asked TEXT, main_concern TEXT, source_channel TEXT, utm_source TEXT, outcome TEXT, loss_reason TEXT);
